import {
  Team,
  Match,
  MatchEvent,
  StandingRow,
  NBAStandingRow,
  NHLStandingRow,
  League,
  Lineup,
} from "./types";

// ─── Helper ────────────────────────────────────────────────────
function badge(abbr: string) {
  return `https://placehold.co/40x40/1E1B3A/7EB6E6?text=${abbr}`;
}

// ─── Leagues ───────────────────────────────────────────────────
export const leagues: League[] = [
  { id: "epl", name: "Premier League", sport: "soccer", country: "England" },
  { id: "laliga", name: "La Liga", sport: "soccer", country: "Spain" },
  { id: "ucl", name: "Champions League", sport: "soccer" },
  { id: "seriea", name: "Serie A", sport: "soccer", country: "Italy" },
  { id: "nba", name: "NBA", sport: "nba", country: "USA" },
  { id: "nfl", name: "NFL", sport: "nfl", country: "USA" },
  { id: "nhl", name: "NHL", sport: "nhl", country: "USA" },
  { id: "mlb", name: "MLB", sport: "mlb", country: "USA" },
];

// ─── Soccer Teams ──────────────────────────────────────────────
const soccerTeams: Record<string, Team> = {
  ARS: { id: "ars", name: "Arsenal", shortName: "ARS", badge: badge("ARS"), sport: "soccer" },
  MCI: { id: "mci", name: "Manchester City", shortName: "MCI", badge: badge("MCI"), sport: "soccer" },
  LIV: { id: "liv", name: "Liverpool", shortName: "LIV", badge: badge("LIV"), sport: "soccer" },
  CHE: { id: "che", name: "Chelsea", shortName: "CHE", badge: badge("CHE"), sport: "soccer" },
  MUN: { id: "mun", name: "Manchester Utd", shortName: "MUN", badge: badge("MUN"), sport: "soccer" },
  TOT: { id: "tot", name: "Tottenham", shortName: "TOT", badge: badge("TOT"), sport: "soccer" },
  NEW: { id: "new", name: "Newcastle", shortName: "NEW", badge: badge("NEW"), sport: "soccer" },
  AVL: { id: "avl", name: "Aston Villa", shortName: "AVL", badge: badge("AVL"), sport: "soccer" },
  BHA: { id: "bha", name: "Brighton", shortName: "BHA", badge: badge("BHA"), sport: "soccer" },
  WHU: { id: "whu", name: "West Ham", shortName: "WHU", badge: badge("WHU"), sport: "soccer" },
  FUL: { id: "ful", name: "Fulham", shortName: "FUL", badge: badge("FUL"), sport: "soccer" },
  BRE: { id: "bre", name: "Brentford", shortName: "BRE", badge: badge("BRE"), sport: "soccer" },
  CRY: { id: "cry", name: "Crystal Palace", shortName: "CRY", badge: badge("CRY"), sport: "soccer" },
  WOL: { id: "wol", name: "Wolves", shortName: "WOL", badge: badge("WOL"), sport: "soccer" },
  EVE: { id: "eve", name: "Everton", shortName: "EVE", badge: badge("EVE"), sport: "soccer" },
  NFO: { id: "nfo", name: "Nott'm Forest", shortName: "NFO", badge: badge("NFO"), sport: "soccer" },
  BOU: { id: "bou", name: "Bournemouth", shortName: "BOU", badge: badge("BOU"), sport: "soccer" },
  IPS: { id: "ips", name: "Ipswich Town", shortName: "IPS", badge: badge("IPS"), sport: "soccer" },
  LEI: { id: "lei", name: "Leicester", shortName: "LEI", badge: badge("LEI"), sport: "soccer" },
  SOU: { id: "sou", name: "Southampton", shortName: "SOU", badge: badge("SOU"), sport: "soccer" },
  RMA: { id: "rma", name: "Real Madrid", shortName: "RMA", badge: badge("RMA"), sport: "soccer" },
  BAR: { id: "bar", name: "Barcelona", shortName: "BAR", badge: badge("BAR"), sport: "soccer" },
  ATM: { id: "atm", name: "Atletico Madrid", shortName: "ATM", badge: badge("ATM"), sport: "soccer" },
  SEV: { id: "sev", name: "Sevilla", shortName: "SEV", badge: badge("SEV"), sport: "soccer" },
  INT: { id: "int", name: "Inter Milan", shortName: "INT", badge: badge("INT"), sport: "soccer" },
  NAP: { id: "nap", name: "Napoli", shortName: "NAP", badge: badge("NAP"), sport: "soccer" },
  JUV: { id: "juv", name: "Juventus", shortName: "JUV", badge: badge("JUV"), sport: "soccer" },
  ACM: { id: "acm", name: "AC Milan", shortName: "ACM", badge: badge("ACM"), sport: "soccer" },
  BAY: { id: "bay", name: "Bayern Munich", shortName: "BAY", badge: badge("BAY"), sport: "soccer" },
  PSG: { id: "psg", name: "Paris Saint-Germain", shortName: "PSG", badge: badge("PSG"), sport: "soccer" },
  DOR: { id: "dor", name: "Borussia Dortmund", shortName: "DOR", badge: badge("DOR"), sport: "soccer" },
};

// ─── NBA Teams ─────────────────────────────────────────────────
const nbaTeams: Record<string, Team> = {
  BOS: { id: "bos", name: "Boston Celtics", shortName: "BOS", badge: badge("BOS"), sport: "nba" },
  NYK: { id: "nyk", name: "New York Knicks", shortName: "NYK", badge: badge("NYK"), sport: "nba" },
  MIL: { id: "mil", name: "Milwaukee Bucks", shortName: "MIL", badge: badge("MIL"), sport: "nba" },
  PHI: { id: "phi", name: "Philadelphia 76ers", shortName: "PHI", badge: badge("PHI"), sport: "nba" },
  CLE: { id: "cle", name: "Cleveland Cavaliers", shortName: "CLE", badge: badge("CLE"), sport: "nba" },
  MIA: { id: "mia", name: "Miami Heat", shortName: "MIA", badge: badge("MIA"), sport: "nba" },
  OKC: { id: "okc", name: "OKC Thunder", shortName: "OKC", badge: badge("OKC"), sport: "nba" },
  DEN: { id: "den", name: "Denver Nuggets", shortName: "DEN", badge: badge("DEN"), sport: "nba" },
  MIN: { id: "min", name: "Minnesota Timberwolves", shortName: "MIN", badge: badge("MIN"), sport: "nba" },
  LAL: { id: "lal", name: "LA Lakers", shortName: "LAL", badge: badge("LAL"), sport: "nba" },
  GSW: { id: "gsw", name: "Golden State Warriors", shortName: "GSW", badge: badge("GSW"), sport: "nba" },
  DAL: { id: "dal", name: "Dallas Mavericks", shortName: "DAL", badge: badge("DAL"), sport: "nba" },
  PHX: { id: "phx", name: "Phoenix Suns", shortName: "PHX", badge: badge("PHX"), sport: "nba" },
  SAC: { id: "sac", name: "Sacramento Kings", shortName: "SAC", badge: badge("SAC"), sport: "nba" },
  IND: { id: "ind", name: "Indiana Pacers", shortName: "IND", badge: badge("IND"), sport: "nba" },
  ORL: { id: "orl", name: "Orlando Magic", shortName: "ORL", badge: badge("ORL"), sport: "nba" },
};

// ─── NFL Teams ─────────────────────────────────────────────────
const nflTeams: Record<string, Team> = {
  KC: { id: "kc", name: "Kansas City Chiefs", shortName: "KC", badge: badge("KC"), sport: "nfl" },
  SF: { id: "sf", name: "San Francisco 49ers", shortName: "SF", badge: badge("SF"), sport: "nfl" },
  BAL: { id: "bal", name: "Baltimore Ravens", shortName: "BAL", badge: badge("BAL"), sport: "nfl" },
  DET: { id: "det", name: "Detroit Lions", shortName: "DET", badge: badge("DET"), sport: "nfl" },
  BUF: { id: "buf", name: "Buffalo Bills", shortName: "BUF", badge: badge("BUF"), sport: "nfl" },
  DAL2: { id: "dal2", name: "Dallas Cowboys", shortName: "DAL", badge: badge("DAL"), sport: "nfl" },
  GB: { id: "gb", name: "Green Bay Packers", shortName: "GB", badge: badge("GB"), sport: "nfl" },
  PHI2: { id: "phi2", name: "Philadelphia Eagles", shortName: "PHI", badge: badge("PHI"), sport: "nfl" },
  HOU: { id: "hou", name: "Houston Texans", shortName: "HOU", badge: badge("HOU"), sport: "nfl" },
  LAR: { id: "lar", name: "LA Rams", shortName: "LAR", badge: badge("LAR"), sport: "nfl" },
};

// ─── NHL Teams ────────────────────────────────────────────────
const nhlTeams: Record<string, Team> = {
  BOS2: { id: "bos2", name: "Boston Bruins", shortName: "BOS", badge: badge("BOS"), sport: "nhl" },
  TOR: { id: "tor", name: "Toronto Maple Leafs", shortName: "TOR", badge: badge("TOR"), sport: "nhl" },
  NYR: { id: "nyr", name: "New York Rangers", shortName: "NYR", badge: badge("NYR"), sport: "nhl" },
  EDM: { id: "edm", name: "Edmonton Oilers", shortName: "EDM", badge: badge("EDM"), sport: "nhl" },
  FLA: { id: "fla", name: "Florida Panthers", shortName: "FLA", badge: badge("FLA"), sport: "nhl" },
  COL: { id: "col", name: "Colorado Avalanche", shortName: "COL", badge: badge("COL"), sport: "nhl" },
  PIT: { id: "pit", name: "Pittsburgh Penguins", shortName: "PIT", badge: badge("PIT"), sport: "nhl" },
  WSH: { id: "wsh", name: "Washington Capitals", shortName: "WSH", badge: badge("WSH"), sport: "nhl" },
  CAR: { id: "car", name: "Carolina Hurricanes", shortName: "CAR", badge: badge("CAR"), sport: "nhl" },
  DAL3: { id: "dal3", name: "Dallas Stars", shortName: "DAL", badge: badge("DAL"), sport: "nhl" },
  VGK: { id: "vgk", name: "Vegas Golden Knights", shortName: "VGK", badge: badge("VGK"), sport: "nhl" },
  WPG: { id: "wpg", name: "Winnipeg Jets", shortName: "WPG", badge: badge("WPG"), sport: "nhl" },
  NJD: { id: "njd", name: "New Jersey Devils", shortName: "NJD", badge: badge("NJD"), sport: "nhl" },
  TB: { id: "tb", name: "Tampa Bay Lightning", shortName: "TB", badge: badge("TB"), sport: "nhl" },
  VAN: { id: "van", name: "Vancouver Canucks", shortName: "VAN", badge: badge("VAN"), sport: "nhl" },
  NSH: { id: "nsh", name: "Nashville Predators", shortName: "NSH", badge: badge("NSH"), sport: "nhl" },
};

// ─── MLB Teams ────────────────────────────────────────────────
const mlbTeams: Record<string, Team> = {
  NYY: { id: "nyy", name: "New York Yankees", shortName: "NYY", badge: badge("NYY"), sport: "mlb" },
  LAD: { id: "lad", name: "Los Angeles Dodgers", shortName: "LAD", badge: badge("LAD"), sport: "mlb" },
  HOU2: { id: "hou2", name: "Houston Astros", shortName: "HOU", badge: badge("HOU"), sport: "mlb" },
  ATL: { id: "atl", name: "Atlanta Braves", shortName: "ATL", badge: badge("ATL"), sport: "mlb" },
  PHI3: { id: "phi3", name: "Philadelphia Phillies", shortName: "PHI", badge: badge("PHI"), sport: "mlb" },
  TEX: { id: "tex", name: "Texas Rangers", shortName: "TEX", badge: badge("TEX"), sport: "mlb" },
  NYM: { id: "nym", name: "New York Mets", shortName: "NYM", badge: badge("NYM"), sport: "mlb" },
  CHC: { id: "chc", name: "Chicago Cubs", shortName: "CHC", badge: badge("CHC"), sport: "mlb" },
  BAL2: { id: "bal2", name: "Baltimore Orioles", shortName: "BAL", badge: badge("BAL"), sport: "mlb" },
  SD: { id: "sd", name: "San Diego Padres", shortName: "SD", badge: badge("SD"), sport: "mlb" },
  MIN2: { id: "min2", name: "Minnesota Twins", shortName: "MIN", badge: badge("MIN"), sport: "mlb" },
  BOS3: { id: "bos3", name: "Boston Red Sox", shortName: "BOS", badge: badge("BOS"), sport: "mlb" },
  SEA: { id: "sea", name: "Seattle Mariners", shortName: "SEA", badge: badge("SEA"), sport: "mlb" },
  MIL2: { id: "mil2", name: "Milwaukee Brewers", shortName: "MIL", badge: badge("MIL"), sport: "mlb" },
  ARI: { id: "ari", name: "Arizona Diamondbacks", shortName: "ARI", badge: badge("ARI"), sport: "mlb" },
  TB2: { id: "tb2", name: "Tampa Bay Rays", shortName: "TB", badge: badge("TB"), sport: "mlb" },
};

// ─── All Teams (flat) ──────────────────────────────────────────
export const allTeams: Team[] = [
  ...Object.values(soccerTeams),
  ...Object.values(nbaTeams),
  ...Object.values(nflTeams),
  ...Object.values(nhlTeams),
  ...Object.values(mlbTeams),
];

// ─── Soccer Matches ────────────────────────────────────────────
export const soccerMatches: Match[] = [
  // --- LIVE ---
  {
    id: "soc-1",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.ARS,
    awayTeam: soccerTeams.CHE,
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    startTime: "2026-02-20T15:00:00Z",
    venue: "Emirates Stadium",
    events: [
      { minute: 12, type: "goal", player: "Bukayo Saka", team: "home", assistedBy: "Martin Odegaard" },
      { minute: 34, type: "goal", player: "Cole Palmer", team: "away" },
      { minute: 55, type: "yellow-card", player: "Enzo Fernandez", team: "away" },
      { minute: 61, type: "goal", player: "Kai Havertz", team: "home", assistedBy: "Declan Rice" },
    ],
    stats: {
      possession: [58, 42],
      shots: [14, 8],
      shotsOnTarget: [6, 3],
      corners: [7, 3],
      fouls: [9, 12],
      yellowCards: [1, 2],
      redCards: [0, 0],
      passes: [456, 312],
      passAccuracy: [89, 83],
    },
  },
  {
    id: "soc-2",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.LIV,
    awayTeam: soccerTeams.MCI,
    homeScore: 1,
    awayScore: 1,
    status: "live",
    minute: 42,
    startTime: "2026-02-20T15:00:00Z",
    venue: "Anfield",
    events: [
      { minute: 18, type: "goal", player: "Mohamed Salah", team: "home", assistedBy: "Trent Alexander-Arnold" },
      { minute: 31, type: "goal", player: "Erling Haaland", team: "away", assistedBy: "Kevin De Bruyne" },
      { minute: 38, type: "yellow-card", player: "Rodri", team: "away" },
    ],
    stats: {
      possession: [46, 54],
      shots: [8, 11],
      shotsOnTarget: [3, 4],
      corners: [4, 6],
      fouls: [7, 8],
      yellowCards: [0, 1],
      redCards: [0, 0],
      passes: [298, 365],
      passAccuracy: [85, 91],
    },
  },
  {
    id: "soc-3",
    sport: "soccer",
    league: "Champions League",
    leagueShort: "UCL",
    homeTeam: soccerTeams.BAR,
    awayTeam: soccerTeams.BAY,
    homeScore: 3,
    awayScore: 2,
    status: "live",
    minute: 78,
    startTime: "2026-02-20T20:00:00Z",
    venue: "Camp Nou",
    events: [
      { minute: 8, type: "goal", player: "Lamine Yamal", team: "home" },
      { minute: 22, type: "goal", player: "Harry Kane", team: "away", assistedBy: "Jamal Musiala" },
      { minute: 45, type: "goal", player: "Robert Lewandowski", team: "home", assistedBy: "Pedri" },
      { minute: 58, type: "goal", player: "Leroy Sane", team: "away" },
      { minute: 71, type: "goal", player: "Raphinha", team: "home", assistedBy: "Lamine Yamal" },
      { minute: 74, type: "yellow-card", player: "Thomas Muller", team: "away" },
    ],
    stats: {
      possession: [61, 39],
      shots: [18, 12],
      shotsOnTarget: [8, 5],
      corners: [9, 4],
      fouls: [10, 14],
      yellowCards: [1, 3],
      redCards: [0, 0],
      passes: [521, 334],
      passAccuracy: [90, 84],
    },
  },
  {
    id: "soc-4",
    sport: "soccer",
    league: "La Liga",
    leagueShort: "LAL",
    homeTeam: soccerTeams.RMA,
    awayTeam: soccerTeams.ATM,
    homeScore: 0,
    awayScore: 0,
    status: "live",
    minute: 15,
    startTime: "2026-02-20T20:00:00Z",
    venue: "Santiago Bernabeu",
    events: [],
    stats: {
      possession: [52, 48],
      shots: [2, 1],
      shotsOnTarget: [1, 0],
      corners: [1, 0],
      fouls: [3, 4],
      yellowCards: [0, 0],
      redCards: [0, 0],
      passes: [112, 98],
      passAccuracy: [88, 85],
    },
  },
  // --- FINISHED ---
  {
    id: "soc-5",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.TOT,
    awayTeam: soccerTeams.MUN,
    homeScore: 3,
    awayScore: 0,
    status: "finished",
    startTime: "2026-02-20T12:30:00Z",
    venue: "Tottenham Hotspur Stadium",
    events: [
      { minute: 14, type: "goal", player: "Son Heung-min", team: "home" },
      { minute: 47, type: "goal", player: "James Maddison", team: "home", assistedBy: "Dejan Kulusevski" },
      { minute: 72, type: "red-card", player: "Bruno Fernandes", team: "away" },
      { minute: 81, type: "goal", player: "Richarlison", team: "home" },
    ],
    stats: {
      possession: [55, 45],
      shots: [16, 6],
      shotsOnTarget: [7, 2],
      corners: [8, 3],
      fouls: [8, 14],
      yellowCards: [1, 3],
      redCards: [0, 1],
      passes: [498, 378],
      passAccuracy: [87, 81],
    },
  },
  {
    id: "soc-6",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.NEW,
    awayTeam: soccerTeams.AVL,
    homeScore: 2,
    awayScore: 2,
    status: "finished",
    startTime: "2026-02-20T12:30:00Z",
    venue: "St James' Park",
    events: [
      { minute: 21, type: "goal", player: "Alexander Isak", team: "home" },
      { minute: 33, type: "goal", player: "Ollie Watkins", team: "away" },
      { minute: 56, type: "goal", player: "Anthony Gordon", team: "home", assistedBy: "Bruno Guimaraes" },
      { minute: 88, type: "goal", player: "Leon Bailey", team: "away" },
    ],
    stats: {
      possession: [51, 49],
      shots: [13, 11],
      shotsOnTarget: [5, 5],
      corners: [6, 5],
      fouls: [11, 10],
      yellowCards: [2, 2],
      redCards: [0, 0],
      passes: [412, 398],
      passAccuracy: [84, 82],
    },
  },
  {
    id: "soc-7",
    sport: "soccer",
    league: "Serie A",
    leagueShort: "SA",
    homeTeam: soccerTeams.INT,
    awayTeam: soccerTeams.JUV,
    homeScore: 1,
    awayScore: 0,
    status: "finished",
    startTime: "2026-02-19T19:45:00Z",
    venue: "San Siro",
    events: [
      { minute: 63, type: "goal", player: "Lautaro Martinez", team: "home", assistedBy: "Nicolo Barella" },
      { minute: 78, type: "yellow-card", player: "Dusan Vlahovic", team: "away" },
    ],
    stats: {
      possession: [53, 47],
      shots: [12, 9],
      shotsOnTarget: [4, 2],
      corners: [5, 4],
      fouls: [12, 11],
      yellowCards: [2, 3],
      redCards: [0, 0],
      passes: [445, 390],
      passAccuracy: [86, 83],
    },
  },
  {
    id: "soc-8",
    sport: "soccer",
    league: "Serie A",
    leagueShort: "SA",
    homeTeam: soccerTeams.NAP,
    awayTeam: soccerTeams.ACM,
    homeScore: 2,
    awayScore: 1,
    status: "finished",
    startTime: "2026-02-19T19:45:00Z",
    venue: "Stadio Diego Armando Maradona",
    events: [
      { minute: 11, type: "goal", player: "Victor Osimhen", team: "home" },
      { minute: 29, type: "goal", player: "Rafael Leao", team: "away" },
      { minute: 67, type: "goal", player: "Khvicha Kvaratskhelia", team: "home", assistedBy: "Stanislav Lobotka" },
    ],
    stats: {
      possession: [48, 52],
      shots: [11, 13],
      shotsOnTarget: [5, 4],
      corners: [4, 7],
      fouls: [13, 9],
      yellowCards: [3, 1],
      redCards: [0, 0],
      passes: [388, 421],
      passAccuracy: [82, 86],
    },
  },
  {
    id: "soc-9",
    sport: "soccer",
    league: "La Liga",
    leagueShort: "LAL",
    homeTeam: soccerTeams.SEV,
    awayTeam: soccerTeams.BAR,
    homeScore: 0,
    awayScore: 4,
    status: "finished",
    startTime: "2026-02-19T20:00:00Z",
    venue: "Ramon Sanchez-Pizjuan",
    events: [
      { minute: 15, type: "goal", player: "Robert Lewandowski", team: "away" },
      { minute: 34, type: "goal", player: "Lamine Yamal", team: "away" },
      { minute: 59, type: "goal", player: "Pedri", team: "away", assistedBy: "Raphinha" },
      { minute: 80, type: "goal", player: "Ferran Torres", team: "away" },
    ],
    stats: {
      possession: [38, 62],
      shots: [6, 19],
      shotsOnTarget: [1, 9],
      corners: [2, 10],
      fouls: [15, 7],
      yellowCards: [4, 0],
      redCards: [0, 0],
      passes: [312, 534],
      passAccuracy: [78, 92],
    },
  },
  // --- UPCOMING ---
  {
    id: "soc-10",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.BHA,
    awayTeam: soccerTeams.WHU,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T15:00:00Z",
    venue: "Amex Stadium",
    events: [],
  },
  {
    id: "soc-11",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.FUL,
    awayTeam: soccerTeams.BRE,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T15:00:00Z",
    venue: "Craven Cottage",
    events: [],
  },
  {
    id: "soc-12",
    sport: "soccer",
    league: "Champions League",
    leagueShort: "UCL",
    homeTeam: soccerTeams.PSG,
    awayTeam: soccerTeams.MCI,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-25T20:00:00Z",
    venue: "Parc des Princes",
    events: [],
  },
  {
    id: "soc-13",
    sport: "soccer",
    league: "Champions League",
    leagueShort: "UCL",
    homeTeam: soccerTeams.ARS,
    awayTeam: soccerTeams.INT,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-25T20:00:00Z",
    venue: "Emirates Stadium",
    events: [],
  },
  {
    id: "soc-14",
    sport: "soccer",
    league: "Serie A",
    leagueShort: "SA",
    homeTeam: soccerTeams.JUV,
    awayTeam: soccerTeams.NAP,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T19:45:00Z",
    venue: "Allianz Stadium",
    events: [],
  },
  {
    id: "soc-15",
    sport: "soccer",
    league: "La Liga",
    leagueShort: "LAL",
    homeTeam: soccerTeams.ATM,
    awayTeam: soccerTeams.SEV,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T20:00:00Z",
    venue: "Metropolitano",
    events: [],
  },
  {
    id: "soc-16",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.EVE,
    awayTeam: soccerTeams.CRY,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T17:30:00Z",
    venue: "Goodison Park",
    events: [],
  },
  {
    id: "soc-17",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: soccerTeams.WOL,
    awayTeam: soccerTeams.NFO,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T15:00:00Z",
    venue: "Molineux",
    events: [],
  },
];

// ─── NBA Matches ───────────────────────────────────────────────
export const nbaMatches: Match[] = [
  // --- LIVE ---
  {
    id: "nba-1",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.BOS,
    awayTeam: nbaTeams.MIL,
    homeScore: 98,
    awayScore: 91,
    status: "live",
    minute: 4, // quarter
    startTime: "2026-02-20T19:30:00Z",
    venue: "TD Garden",
    events: [],
  },
  {
    id: "nba-2",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.LAL,
    awayTeam: nbaTeams.GSW,
    homeScore: 67,
    awayScore: 72,
    status: "live",
    minute: 3, // quarter
    startTime: "2026-02-20T22:00:00Z",
    venue: "Crypto.com Arena",
    events: [],
  },
  {
    id: "nba-3",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.OKC,
    awayTeam: nbaTeams.DEN,
    homeScore: 54,
    awayScore: 48,
    status: "live",
    minute: 2, // quarter
    startTime: "2026-02-20T20:00:00Z",
    venue: "Paycom Center",
    events: [],
  },
  // --- FINISHED ---
  {
    id: "nba-4",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.NYK,
    awayTeam: nbaTeams.PHI,
    homeScore: 118,
    awayScore: 105,
    status: "finished",
    startTime: "2026-02-19T19:00:00Z",
    venue: "Madison Square Garden",
    events: [],
  },
  {
    id: "nba-5",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.CLE,
    awayTeam: nbaTeams.MIA,
    homeScore: 112,
    awayScore: 108,
    status: "finished",
    startTime: "2026-02-19T19:30:00Z",
    venue: "Rocket Mortgage FieldHouse",
    events: [],
  },
  {
    id: "nba-6",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.DAL,
    awayTeam: nbaTeams.PHX,
    homeScore: 121,
    awayScore: 119,
    status: "finished",
    startTime: "2026-02-19T21:30:00Z",
    venue: "American Airlines Center",
    events: [],
  },
  // --- UPCOMING ---
  {
    id: "nba-7",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.MIN,
    awayTeam: nbaTeams.SAC,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T20:00:00Z",
    venue: "Target Center",
    events: [],
  },
  {
    id: "nba-8",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.IND,
    awayTeam: nbaTeams.ORL,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-21T19:00:00Z",
    venue: "Gainbridge Fieldhouse",
    events: [],
  },
  {
    id: "nba-9",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: nbaTeams.GSW,
    awayTeam: nbaTeams.BOS,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T20:30:00Z",
    venue: "Chase Center",
    events: [],
  },
];

// ─── NFL Matches ───────────────────────────────────────────────
export const nflMatches: Match[] = [
  // --- LIVE ---
  {
    id: "nfl-1",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.KC,
    awayTeam: nflTeams.BUF,
    homeScore: 21,
    awayScore: 17,
    status: "live",
    minute: 3, // quarter
    startTime: "2026-02-20T20:15:00Z",
    venue: "Arrowhead Stadium",
    events: [],
  },
  // --- FINISHED ---
  {
    id: "nfl-2",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.SF,
    awayTeam: nflTeams.DET,
    homeScore: 34,
    awayScore: 31,
    status: "finished",
    startTime: "2026-02-19T16:25:00Z",
    venue: "Levi's Stadium",
    events: [],
  },
  {
    id: "nfl-3",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.BAL,
    awayTeam: nflTeams.PHI2,
    homeScore: 27,
    awayScore: 24,
    status: "finished",
    startTime: "2026-02-19T13:00:00Z",
    venue: "M&T Bank Stadium",
    events: [],
  },
  {
    id: "nfl-4",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.GB,
    awayTeam: nflTeams.DAL2,
    homeScore: 28,
    awayScore: 14,
    status: "finished",
    startTime: "2026-02-19T16:25:00Z",
    venue: "Lambeau Field",
    events: [],
  },
  // --- UPCOMING ---
  {
    id: "nfl-5",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.HOU,
    awayTeam: nflTeams.LAR,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T13:00:00Z",
    venue: "NRG Stadium",
    events: [],
  },
  {
    id: "nfl-6",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.DET,
    awayTeam: nflTeams.KC,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T16:25:00Z",
    venue: "Ford Field",
    events: [],
  },
  {
    id: "nfl-7",
    sport: "nfl",
    league: "NFL",
    leagueShort: "NFL",
    homeTeam: nflTeams.BUF,
    awayTeam: nflTeams.SF,
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: "2026-02-22T20:15:00Z",
    venue: "Highmark Stadium",
    events: [],
  },
];

// ─── All Matches ───────────────────────────────────────────────
export const allMatches: Match[] = [
  ...soccerMatches,
  ...nbaMatches,
  ...nflMatches,
];

// ─── Premier League Standings ──────────────────────────────────
export const eplStandings: StandingRow[] = [
  { position: 1, team: soccerTeams.ARS, played: 25, won: 19, drawn: 4, lost: 2, goalsFor: 56, goalsAgainst: 18, goalDifference: 38, points: 61, form: ["W", "W", "W", "D", "W"] },
  { position: 2, team: soccerTeams.LIV, played: 25, won: 18, drawn: 5, lost: 2, goalsFor: 52, goalsAgainst: 20, goalDifference: 32, points: 59, form: ["W", "D", "W", "W", "D"] },
  { position: 3, team: soccerTeams.MCI, played: 25, won: 17, drawn: 4, lost: 4, goalsFor: 55, goalsAgainst: 25, goalDifference: 30, points: 55, form: ["W", "L", "W", "W", "W"] },
  { position: 4, team: soccerTeams.CHE, played: 25, won: 14, drawn: 6, lost: 5, goalsFor: 48, goalsAgainst: 28, goalDifference: 20, points: 48, form: ["D", "W", "L", "W", "W"] },
  { position: 5, team: soccerTeams.TOT, played: 25, won: 14, drawn: 3, lost: 8, goalsFor: 50, goalsAgainst: 32, goalDifference: 18, points: 45, form: ["W", "W", "W", "L", "W"] },
  { position: 6, team: soccerTeams.NEW, played: 25, won: 13, drawn: 5, lost: 7, goalsFor: 44, goalsAgainst: 30, goalDifference: 14, points: 44, form: ["D", "W", "D", "W", "L"] },
  { position: 7, team: soccerTeams.AVL, played: 25, won: 12, drawn: 6, lost: 7, goalsFor: 42, goalsAgainst: 34, goalDifference: 8, points: 42, form: ["W", "D", "L", "W", "D"] },
  { position: 8, team: soccerTeams.MUN, played: 25, won: 11, drawn: 5, lost: 9, goalsFor: 36, goalsAgainst: 33, goalDifference: 3, points: 38, form: ["L", "L", "W", "D", "W"] },
  { position: 9, team: soccerTeams.BHA, played: 25, won: 10, drawn: 7, lost: 8, goalsFor: 40, goalsAgainst: 36, goalDifference: 4, points: 37, form: ["D", "W", "D", "L", "W"] },
  { position: 10, team: soccerTeams.BRE, played: 25, won: 10, drawn: 5, lost: 10, goalsFor: 38, goalsAgainst: 38, goalDifference: 0, points: 35, form: ["W", "L", "W", "L", "D"] },
  { position: 11, team: soccerTeams.NFO, played: 25, won: 10, drawn: 4, lost: 11, goalsFor: 32, goalsAgainst: 35, goalDifference: -3, points: 34, form: ["L", "W", "W", "L", "L"] },
  { position: 12, team: soccerTeams.FUL, played: 25, won: 9, drawn: 6, lost: 10, goalsFor: 34, goalsAgainst: 36, goalDifference: -2, points: 33, form: ["D", "L", "W", "D", "W"] },
  { position: 13, team: soccerTeams.WHU, played: 25, won: 9, drawn: 5, lost: 11, goalsFor: 30, goalsAgainst: 38, goalDifference: -8, points: 32, form: ["L", "W", "L", "W", "L"] },
  { position: 14, team: soccerTeams.CRY, played: 25, won: 8, drawn: 7, lost: 10, goalsFor: 28, goalsAgainst: 34, goalDifference: -6, points: 31, form: ["D", "D", "L", "W", "D"] },
  { position: 15, team: soccerTeams.BOU, played: 25, won: 8, drawn: 5, lost: 12, goalsFor: 32, goalsAgainst: 42, goalDifference: -10, points: 29, form: ["L", "W", "L", "L", "W"] },
  { position: 16, team: soccerTeams.WOL, played: 25, won: 7, drawn: 5, lost: 13, goalsFor: 26, goalsAgainst: 40, goalDifference: -14, points: 26, form: ["L", "L", "D", "W", "L"] },
  { position: 17, team: soccerTeams.EVE, played: 25, won: 6, drawn: 7, lost: 12, goalsFor: 24, goalsAgainst: 38, goalDifference: -14, points: 25, form: ["D", "L", "L", "D", "L"] },
  { position: 18, team: soccerTeams.LEI, played: 25, won: 5, drawn: 5, lost: 15, goalsFor: 22, goalsAgainst: 48, goalDifference: -26, points: 20, form: ["L", "L", "W", "L", "L"] },
  { position: 19, team: soccerTeams.IPS, played: 25, won: 4, drawn: 4, lost: 17, goalsFor: 18, goalsAgainst: 50, goalDifference: -32, points: 16, form: ["L", "L", "L", "D", "L"] },
  { position: 20, team: soccerTeams.SOU, played: 25, won: 2, drawn: 6, lost: 17, goalsFor: 14, goalsAgainst: 52, goalDifference: -38, points: 12, form: ["L", "D", "L", "L", "L"] },
];

// ─── NBA Eastern Conference Standings ──────────────────────────
export const nbaEastStandings: NBAStandingRow[] = [
  { position: 1, team: nbaTeams.BOS, played: 55, won: 40, lost: 15, winPct: ".727", gamesBehind: "-", streak: "W5", last10: "8-2" },
  { position: 2, team: nbaTeams.CLE, played: 55, won: 38, lost: 17, winPct: ".691", gamesBehind: "2.0", streak: "W3", last10: "7-3" },
  { position: 3, team: nbaTeams.NYK, played: 56, won: 37, lost: 19, winPct: ".661", gamesBehind: "3.5", streak: "W2", last10: "6-4" },
  { position: 4, team: nbaTeams.MIL, played: 55, won: 34, lost: 21, winPct: ".618", gamesBehind: "6.0", streak: "L1", last10: "6-4" },
  { position: 5, team: nbaTeams.ORL, played: 56, won: 33, lost: 23, winPct: ".589", gamesBehind: "7.5", streak: "W1", last10: "5-5" },
  { position: 6, team: nbaTeams.IND, played: 55, won: 32, lost: 23, winPct: ".582", gamesBehind: "8.0", streak: "L2", last10: "4-6" },
  { position: 7, team: nbaTeams.PHI, played: 55, won: 30, lost: 25, winPct: ".545", gamesBehind: "10.0", streak: "L1", last10: "5-5" },
  { position: 8, team: nbaTeams.MIA, played: 56, won: 28, lost: 28, winPct: ".500", gamesBehind: "12.5", streak: "W1", last10: "4-6" },
];

// ─── NBA Western Conference Standings ──────────────────────────
export const nbaWestStandings: NBAStandingRow[] = [
  { position: 1, team: nbaTeams.OKC, played: 55, won: 42, lost: 13, winPct: ".764", gamesBehind: "-", streak: "W8", last10: "9-1" },
  { position: 2, team: nbaTeams.DEN, played: 55, won: 36, lost: 19, winPct: ".655", gamesBehind: "6.0", streak: "W2", last10: "7-3" },
  { position: 3, team: nbaTeams.MIN, played: 56, won: 35, lost: 21, winPct: ".625", gamesBehind: "7.5", streak: "L1", last10: "6-4" },
  { position: 4, team: nbaTeams.DAL, played: 55, won: 33, lost: 22, winPct: ".600", gamesBehind: "9.0", streak: "W1", last10: "7-3" },
  { position: 5, team: nbaTeams.LAL, played: 56, won: 32, lost: 24, winPct: ".571", gamesBehind: "10.5", streak: "L2", last10: "5-5" },
  { position: 6, team: nbaTeams.PHX, played: 55, won: 31, lost: 24, winPct: ".564", gamesBehind: "11.0", streak: "W1", last10: "5-5" },
  { position: 7, team: nbaTeams.SAC, played: 56, won: 29, lost: 27, winPct: ".518", gamesBehind: "13.5", streak: "L3", last10: "3-7" },
  { position: 8, team: nbaTeams.GSW, played: 56, won: 28, lost: 28, winPct: ".500", gamesBehind: "14.5", streak: "W2", last10: "5-5" },
];

// ─── Lineups (Arsenal vs Chelsea example) ──────────────────────
export const sampleLineups: Record<string, { home: Lineup; away: Lineup }> = {
  "soc-1": {
    home: {
      formation: "4-3-3",
      starters: [
        { number: 1, name: "David Raya", position: "GK" },
        { number: 4, name: "Ben White", position: "RB" },
        { number: 2, name: "William Saliba", position: "CB" },
        { number: 6, name: "Gabriel", position: "CB" },
        { number: 35, name: "Oleksandr Zinchenko", position: "LB" },
        { number: 41, name: "Declan Rice", position: "CM" },
        { number: 5, name: "Thomas Partey", position: "CM" },
        { number: 8, name: "Martin Odegaard", position: "AM" },
        { number: 7, name: "Bukayo Saka", position: "RW" },
        { number: 29, name: "Kai Havertz", position: "ST" },
        { number: 11, name: "Gabriel Martinelli", position: "LW" },
      ],
      substitutes: [
        { number: 22, name: "Aaron Ramsdale", position: "GK" },
        { number: 18, name: "Takehiro Tomiyasu", position: "DEF" },
        { number: 15, name: "Jakub Kiwior", position: "DEF" },
        { number: 20, name: "Jorginho", position: "MID" },
        { number: 21, name: "Fabio Vieira", position: "MID" },
        { number: 24, name: "Reiss Nelson", position: "FWD" },
        { number: 14, name: "Eddie Nketiah", position: "FWD" },
      ],
    },
    away: {
      formation: "4-2-3-1",
      starters: [
        { number: 1, name: "Robert Sanchez", position: "GK" },
        { number: 24, name: "Reece James", position: "RB" },
        { number: 26, name: "Levi Colwill", position: "CB" },
        { number: 6, name: "Thiago Silva", position: "CB" },
        { number: 21, name: "Ben Chilwell", position: "LB" },
        { number: 25, name: "Moises Caicedo", position: "DM" },
        { number: 8, name: "Enzo Fernandez", position: "DM" },
        { number: 20, name: "Cole Palmer", position: "AM" },
        { number: 7, name: "Raheem Sterling", position: "RW" },
        { number: 18, name: "Nicolas Jackson", position: "ST" },
        { number: 15, name: "Noni Madueke", position: "LW" },
      ],
      substitutes: [
        { number: 13, name: "Marcus Bettinelli", position: "GK" },
        { number: 2, name: "Axel Disasi", position: "DEF" },
        { number: 14, name: "Trevoh Chalobah", position: "DEF" },
        { number: 17, name: "Carney Chukwuemeka", position: "MID" },
        { number: 23, name: "Conor Gallagher", position: "MID" },
        { number: 11, name: "Mykhailo Mudryk", position: "FWD" },
        { number: 19, name: "Armando Broja", position: "FWD" },
      ],
    },
  },
};

// ─── Helper: find match by id ──────────────────────────────────
export function getMatchById(id: string): Match | undefined {
  return allMatches.find((m) => m.id === id);
}

// ─── Helper: get matches by sport ──────────────────────────────
export function getMatchesBySport(sport: string): Match[] {
  return allMatches.filter((m) => m.sport === sport);
}

// ─── Helper: group matches by league ───────────────────────────
export function groupMatchesByLeague(matches: Match[]): Record<string, Match[]> {
  return matches.reduce<Record<string, Match[]>>((acc, match) => {
    const key = match.league;
    if (!acc[key]) acc[key] = [];
    acc[key].push(match);
    return acc;
  }, {});
}
