import type { Match, MatchEvent, MatchStats, SportDetail, Sport } from "../types";
import { soccerTeams, laLigaTeams, bundesligaTeams, serieATeams, nbaTeams, nflTeams, nhlTeams, mlbTeams } from "./teams";

// Helper to get team object by index in sport array
const s = (i: number) => soccerTeams[i].team;
const n = (i: number) => nbaTeams[i].team;
const f = (i: number) => nflTeams[i].team;
const h = (i: number) => nhlTeams[i].team;
const b = (i: number) => mlbTeams[i].team;

// Dates relative to "today" (mock assumes 2026-02-27)
const today = "2026-02-27";
const yesterday = "2026-02-26";
const twoDaysAgo = "2026-02-25";
const tomorrow = "2026-02-28";
const dayAfter = "2026-03-01";

// ═══════════════════════════════════════════════════════════════
// SOCCER MATCHES
// ═══════════════════════════════════════════════════════════════

const soccerEvents1: MatchEvent[] = [
  { minute: 12, type: "goal", player: "Bukayo Saka", team: "home", assistedBy: "Martin Ødegaard" },
  { minute: 34, type: "goal", player: "Erling Haaland", team: "away", assistedBy: "Kevin De Bruyne" },
  { minute: 38, type: "yellow-card", player: "Rodri", team: "away" },
  { minute: 55, type: "goal", player: "Kai Havertz", team: "home", assistedBy: "Bukayo Saka" },
  { minute: 67, type: "substitution", player: "Leandro Trossard", team: "home", playerOut: "Gabriel Martinelli" },
  { minute: 72, type: "yellow-card", player: "Declan Rice", team: "home" },
  { minute: 81, type: "goal", player: "Phil Foden", team: "away", assistedBy: "Bernardo Silva" },
  { minute: 88, type: "red-card", player: "Manuel Akanji", team: "away" },
];

const soccerStats1: MatchStats = {
  possession: [52, 48],
  shots: [15, 12],
  shotsOnTarget: [6, 5],
  corners: [7, 4],
  fouls: [11, 14],
  yellowCards: [1, 1],
  redCards: [0, 1],
  passes: [487, 452],
  passAccuracy: [87, 89],
};

const soccerEvents2: MatchEvent[] = [
  { minute: 23, type: "goal", player: "Mohamed Salah", team: "home", assistedBy: "Trent Alexander-Arnold" },
  { minute: 45, type: "yellow-card", player: "Enzo Fernández", team: "away" },
  { minute: 58, type: "goal", player: "Mohamed Salah", team: "home" },
  { minute: 71, type: "goal", player: "Cole Palmer", team: "away", assistedBy: "Nicolas Jackson" },
  { minute: 78, type: "substitution", player: "Diogo Jota", team: "home", playerOut: "Darwin Núñez" },
];

const soccerEvents3: MatchEvent[] = [
  { minute: 15, type: "goal", player: "Alexander Isak", team: "home", assistedBy: "Anthony Gordon" },
  { minute: 29, type: "yellow-card", player: "Casemiro", team: "away" },
  { minute: 44, type: "goal", player: "Alexander Isak", team: "home", assistedBy: "Bruno Guimarães" },
  { minute: 62, type: "goal", player: "Marcus Rashford", team: "away", assistedBy: "Bruno Fernandes" },
  { minute: 73, type: "substitution", player: "Alejandro Garnacho", team: "away", playerOut: "Antony" },
  { minute: 85, type: "goal", player: "Alexander Isak", team: "home", assistedBy: "Sandro Tonali" },
];

export const soccerMatches: Match[] = [
  // --- FINISHED ---
  {
    id: "mock-soccer-m1",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(0),
    awayTeam: s(1),
    homeScore: 2,
    awayScore: 2,
    status: "finished",
    statusDetail: "ft",
    startTime: `${twoDaysAgo}T15:00:00Z`,
    events: soccerEvents1,
    stats: soccerStats1,
    venue: "Emirates Stadium",
    source: "mock",
    sportDetail: { htScore: { home: 1, away: 1 } },
    referee: { name: "Michael Oliver", nationality: "England" },
    matchday: 27,
    homeForm: ["W", "W", "D", "W", "L"],
    awayForm: ["W", "D", "W", "W", "W"],
  },
  {
    id: "mock-soccer-m2",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(2),
    awayTeam: s(3),
    homeScore: 2,
    awayScore: 1,
    status: "finished",
    statusDetail: "ft",
    startTime: `${twoDaysAgo}T17:30:00Z`,
    events: soccerEvents2,
    stats: {
      possession: [58, 42],
      shots: [18, 9],
      shotsOnTarget: [7, 3],
      corners: [8, 3],
      fouls: [9, 12],
      yellowCards: [0, 1],
      redCards: [0, 0],
      passes: [562, 378],
      passAccuracy: [91, 84],
    },
    venue: "Anfield",
    source: "mock",
    sportDetail: { htScore: { home: 1, away: 0 } },
    referee: { name: "Anthony Taylor", nationality: "England" },
    matchday: 27,
    homeForm: ["W", "W", "W", "D", "W"],
    awayForm: ["L", "W", "D", "L", "W"],
  },
  {
    id: "mock-soccer-m3",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(6),
    awayTeam: s(4),
    homeScore: 3,
    awayScore: 1,
    status: "finished",
    statusDetail: "ft",
    startTime: `${yesterday}T20:00:00Z`,
    events: soccerEvents3,
    stats: {
      possession: [46, 54],
      shots: [14, 11],
      shotsOnTarget: [6, 4],
      corners: [5, 6],
      fouls: [10, 13],
      yellowCards: [0, 1],
      redCards: [0, 0],
      passes: [398, 467],
      passAccuracy: [83, 86],
    },
    venue: "St James' Park",
    source: "mock",
    sportDetail: { htScore: { home: 2, away: 0 } },
    referee: { name: "Stuart Attwell", nationality: "England" },
    matchday: 27,
    homeForm: ["W", "D", "W", "W", "L"],
    awayForm: ["L", "L", "D", "W", "L"],
  },
  // --- LIVE ---
  {
    id: "mock-soccer-m4",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(5),
    awayTeam: s(7),
    homeScore: 1,
    awayScore: 0,
    status: "live",
    clock: { value: 63, displayValue: "63'" },
    startTime: `${today}T15:00:00Z`,
    events: [
      { minute: 31, type: "goal", player: "Son Heung-min", team: "home", assistedBy: "James Maddison" },
      { minute: 52, type: "yellow-card", player: "Boubacar Kamara", team: "away" },
    ],
    venue: "Tottenham Hotspur Stadium",
    source: "mock",
    sportDetail: { htScore: { home: 1, away: 0 } },
    homeForm: ["D", "W", "L", "W", "W"],
    awayForm: ["W", "W", "W", "D", "L"],
  },
  {
    id: "mock-soccer-m5",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(0),
    awayTeam: s(2),
    homeScore: 0,
    awayScore: 0,
    status: "live",
    clock: { value: 28, displayValue: "28'" },
    startTime: `${today}T17:30:00Z`,
    events: [
      { minute: 18, type: "yellow-card", player: "Declan Rice", team: "home" },
    ],
    venue: "Emirates Stadium",
    source: "mock",
    homeForm: ["W", "W", "D", "W", "L"],
    awayForm: ["W", "W", "W", "D", "W"],
  },
  // --- UPCOMING ---
  {
    id: "mock-soccer-m6",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(1),
    awayTeam: s(4),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T15:00:00Z`,
    events: [],
    venue: "Etihad Stadium",
    source: "mock",
    matchday: 28,
    homeForm: ["W", "D", "W", "W", "W"],
    awayForm: ["L", "L", "D", "W", "L"],
  },
  {
    id: "mock-soccer-m7",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(3),
    awayTeam: s(6),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T17:30:00Z`,
    events: [],
    venue: "Stamford Bridge",
    source: "mock",
    matchday: 28,
  },
  {
    id: "mock-soccer-m8",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(7),
    awayTeam: s(5),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T14:00:00Z`,
    events: [],
    venue: "Villa Park",
    source: "mock",
    matchday: 28,
  },
  {
    id: "mock-soccer-m9",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(4),
    awayTeam: s(3),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T16:30:00Z`,
    events: [],
    venue: "Old Trafford",
    source: "mock",
    matchday: 28,
  },
  {
    id: "mock-soccer-m10",
    sport: "soccer",
    league: "Premier League",
    leagueShort: "EPL",
    homeTeam: s(2),
    awayTeam: s(1),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T16:30:00Z`,
    events: [],
    venue: "Anfield",
    source: "mock",
    matchday: 28,
  },
];

// ═══════════════════════════════════════════════════════════════
// MULTI-LEAGUE SOCCER MATCHES
// ═══════════════════════════════════════════════════════════════

const ll = (i: number) => laLigaTeams[i].team;
const bl = (i: number) => bundesligaTeams[i].team;
const sa = (i: number) => serieATeams[i].team;

export const multiLeagueSoccerMatches: Match[] = [
  // La Liga
  {
    id: "mock-soccer-m11", sport: "soccer", league: "La Liga", leagueShort: "LL",
    homeTeam: ll(0), awayTeam: ll(2),
    homeScore: 2, awayScore: 1, status: "finished",
    startTime: `${today}T15:00:00Z`,
    events: [
      { type: "goal", minute: 23, player: "Jude Bellingham", team: "home" },
      { type: "goal", minute: 67, player: "Antoine Griezmann", team: "away" },
      { type: "goal", minute: 89, player: "Vinícius Jr.", team: "home" },
    ],
    sportDetail: { htScore: { home: 1, away: 0 } },
    venue: "Santiago Bernabéu", source: "mock", matchday: 26,
  },
  {
    id: "mock-soccer-m12", sport: "soccer", league: "La Liga", leagueShort: "LL",
    homeTeam: ll(1), awayTeam: ll(0),
    homeScore: 1, awayScore: 1, status: "live",
    startTime: `${today}T20:00:00Z`,
    clock: { value: 62, displayValue: "62'" },
    events: [
      { type: "goal", minute: 15, player: "Robert Lewandowski", team: "home" },
      { type: "goal", minute: 55, player: "Kylian Mbappé", team: "away" },
    ],
    venue: "Spotify Camp Nou", source: "mock", matchday: 26,
  },
  {
    id: "mock-soccer-m13", sport: "soccer", league: "La Liga", leagueShort: "LL",
    homeTeam: ll(2), awayTeam: ll(1),
    homeScore: null, awayScore: null, status: "upcoming",
    startTime: `${dayAfter}T18:00:00Z`,
    events: [],
    venue: "Metropolitano", source: "mock", matchday: 27,
  },
  // Bundesliga
  {
    id: "mock-soccer-m14", sport: "soccer", league: "Bundesliga", leagueShort: "BL",
    homeTeam: bl(0), awayTeam: bl(1),
    homeScore: 3, awayScore: 2, status: "finished",
    startTime: `${today}T14:30:00Z`,
    events: [
      { type: "goal", minute: 12, player: "Harry Kane", team: "home" },
      { type: "goal", minute: 34, player: "Niclas Füllkrug", team: "away" },
      { type: "goal", minute: 45, player: "Harry Kane", team: "home" },
      { type: "goal", minute: 58, player: "Karim Adeyemi", team: "away" },
      { type: "goal", minute: 71, player: "Jamal Musiala", team: "home" },
    ],
    sportDetail: { htScore: { home: 2, away: 1 } },
    venue: "Allianz Arena", source: "mock", matchday: 24,
  },
  {
    id: "mock-soccer-m15", sport: "soccer", league: "Bundesliga", leagueShort: "BL",
    homeTeam: bl(1), awayTeam: bl(0),
    homeScore: 0, awayScore: 0, status: "live",
    startTime: `${today}T17:30:00Z`,
    clock: { value: 28, displayValue: "28'" },
    events: [],
    venue: "Signal Iduna Park", source: "mock", matchday: 25,
  },
  {
    id: "mock-soccer-m16", sport: "soccer", league: "Bundesliga", leagueShort: "BL",
    homeTeam: bl(0), awayTeam: s(0),
    homeScore: null, awayScore: null, status: "upcoming",
    startTime: `${dayAfter}T20:00:00Z`,
    events: [],
    venue: "Allianz Arena", source: "mock", matchday: 25,
  },
  // Serie A
  {
    id: "mock-soccer-m17", sport: "soccer", league: "Serie A", leagueShort: "SA",
    homeTeam: sa(0), awayTeam: sa(1),
    homeScore: 1, awayScore: 0, status: "finished",
    startTime: `${today}T17:45:00Z`,
    events: [
      { type: "goal", minute: 73, player: "Lautaro Martínez", team: "home" },
    ],
    sportDetail: { htScore: { home: 0, away: 0 } },
    venue: "San Siro", source: "mock", matchday: 27,
  },
  {
    id: "mock-soccer-m18", sport: "soccer", league: "Serie A", leagueShort: "SA",
    homeTeam: sa(1), awayTeam: sa(0),
    homeScore: 2, awayScore: 2, status: "live",
    startTime: `${today}T19:45:00Z`,
    clock: { value: 78, displayValue: "78'" },
    events: [
      { type: "goal", minute: 11, player: "Dušan Vlahović", team: "home" },
      { type: "goal", minute: 33, player: "Marcus Thuram", team: "away" },
      { type: "goal", minute: 55, player: "Federico Chiesa", team: "home" },
      { type: "goal", minute: 70, player: "Lautaro Martínez", team: "away" },
    ],
    venue: "Allianz Stadium", source: "mock", matchday: 27,
  },
  // Champions League
  {
    id: "mock-soccer-m19", sport: "soccer", league: "UEFA Champions League", leagueShort: "UCL",
    homeTeam: s(0), awayTeam: ll(0),
    homeScore: 1, awayScore: 1, status: "live",
    startTime: `${today}T20:00:00Z`,
    clock: { value: 44, displayValue: "44'" },
    events: [
      { type: "goal", minute: 18, player: "Bukayo Saka", team: "home" },
      { type: "goal", minute: 37, player: "Jude Bellingham", team: "away" },
    ],
    venue: "Emirates Stadium", source: "mock", matchday: 7,
  },
  {
    id: "mock-soccer-m20", sport: "soccer", league: "UEFA Champions League", leagueShort: "UCL",
    homeTeam: bl(0), awayTeam: sa(0),
    homeScore: 2, awayScore: 0, status: "finished",
    startTime: `${today}T20:00:00Z`,
    events: [
      { type: "goal", minute: 29, player: "Harry Kane", team: "home" },
      { type: "goal", minute: 64, player: "Jamal Musiala", team: "home" },
    ],
    sportDetail: { htScore: { home: 1, away: 0 } },
    venue: "Allianz Arena", source: "mock", matchday: 7,
  },
  {
    id: "mock-soccer-m21", sport: "soccer", league: "UEFA Champions League", leagueShort: "UCL",
    homeTeam: ll(1), awayTeam: s(2),
    homeScore: null, awayScore: null, status: "upcoming",
    startTime: `${dayAfter}T20:00:00Z`,
    events: [],
    venue: "Spotify Camp Nou", source: "mock", matchday: 8,
  },
];

// ═══════════════════════════════════════════════════════════════
// NBA MATCHES
// ═══════════════════════════════════════════════════════════════

function nbaDetail(
  home: number[],
  away: number[],
  homeRec: string,
  awayRec: string,
  leaders?: SportDetail["leaders"]
): SportDetail {
  return { linescores: { home, away }, homeRecord: homeRec, awayRecord: awayRec, leaders };
}

export const nbaMatches: Match[] = [
  // --- FINISHED ---
  {
    id: "mock-nba-m1",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(0),
    awayTeam: n(1),
    homeScore: 108,
    awayScore: 117,
    status: "finished",
    startTime: `${twoDaysAgo}T00:30:00Z`,
    events: [],
    venue: "Crypto.com Arena",
    source: "mock",
    sportDetail: nbaDetail([28, 25, 30, 25], [32, 27, 28, 30], "32-24", "40-16", [
      { category: "Points", playerName: "LeBron James", displayValue: "34 PTS", teamSide: "home" },
      { category: "Rebounds", playerName: "Anthony Davis", displayValue: "14 REB", teamSide: "home" },
      { category: "Points", playerName: "Jayson Tatum", displayValue: "38 PTS", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nba-m2",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(2),
    awayTeam: n(3),
    homeScore: 122,
    awayScore: 118,
    status: "finished",
    startTime: `${twoDaysAgo}T03:00:00Z`,
    events: [],
    venue: "Chase Center",
    source: "mock",
    sportDetail: nbaDetail([30, 32, 28, 32], [29, 30, 31, 28], "28-28", "35-21", [
      { category: "Points", playerName: "Stephen Curry", displayValue: "41 PTS", teamSide: "home" },
      { category: "Points", playerName: "Giannis Antetokounmpo", displayValue: "36 PTS", teamSide: "away" },
      { category: "Assists", playerName: "Damian Lillard", displayValue: "11 AST", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nba-m3",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(4),
    awayTeam: n(5),
    homeScore: 115,
    awayScore: 102,
    status: "finished",
    startTime: `${yesterday}T01:00:00Z`,
    events: [],
    venue: "Ball Arena",
    source: "mock",
    sportDetail: nbaDetail([30, 28, 32, 25], [24, 26, 28, 24], "36-20", "29-27", [
      { category: "Points", playerName: "Nikola Jokić", displayValue: "28 PTS", teamSide: "home" },
      { category: "Assists", playerName: "Nikola Jokić", displayValue: "14 AST", teamSide: "home" },
      { category: "Points", playerName: "Joel Embiid", displayValue: "31 PTS", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nba-m4",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(6),
    awayTeam: n(7),
    homeScore: 105,
    awayScore: 110,
    status: "finished",
    startTime: `${yesterday}T00:00:00Z`,
    events: [],
    venue: "Kaseya Center",
    source: "mock",
    sportDetail: nbaDetail([22, 28, 30, 25], [28, 25, 27, 30], "30-26", "33-23", [
      { category: "Points", playerName: "Kevin Durant", displayValue: "35 PTS", teamSide: "away" },
      { category: "Points", playerName: "Jimmy Butler", displayValue: "27 PTS", teamSide: "home" },
    ]),
  },
  // --- LIVE ---
  {
    id: "mock-nba-m5",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(1),
    awayTeam: n(4),
    homeScore: 78,
    awayScore: 72,
    status: "live",
    clock: { value: 3, displayValue: "Q3 5:42" },
    startTime: `${today}T00:30:00Z`,
    events: [],
    venue: "TD Garden",
    source: "mock",
    sportDetail: nbaDetail([28, 26, 24], [22, 25, 25], "40-16", "36-20", [
      { category: "Points", playerName: "Jaylen Brown", displayValue: "22 PTS", teamSide: "home" },
      { category: "Points", playerName: "Jamal Murray", displayValue: "19 PTS", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nba-m6",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(0),
    awayTeam: n(3),
    homeScore: 55,
    awayScore: 58,
    status: "live",
    clock: { value: 2, displayValue: "Q2 2:18" },
    startTime: `${today}T03:00:00Z`,
    events: [],
    venue: "Crypto.com Arena",
    source: "mock",
    sportDetail: nbaDetail([28, 27], [30, 28], "32-24", "35-21", [
      { category: "Points", playerName: "LeBron James", displayValue: "18 PTS", teamSide: "home" },
      { category: "Points", playerName: "Giannis Antetokounmpo", displayValue: "21 PTS", teamSide: "away" },
    ]),
  },
  // --- UPCOMING ---
  {
    id: "mock-nba-m7",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(7),
    awayTeam: n(2),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T02:00:00Z`,
    events: [],
    venue: "Footprint Center",
    source: "mock",
    sportDetail: { homeRecord: "33-23", awayRecord: "28-28" },
  },
  {
    id: "mock-nba-m8",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(5),
    awayTeam: n(6),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T00:00:00Z`,
    events: [],
    venue: "Wells Fargo Center",
    source: "mock",
    sportDetail: { homeRecord: "29-27", awayRecord: "30-26" },
  },
  {
    id: "mock-nba-m9",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(3),
    awayTeam: n(1),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T00:30:00Z`,
    events: [],
    venue: "Fiserv Forum",
    source: "mock",
    sportDetail: { homeRecord: "35-21", awayRecord: "40-16" },
  },
  {
    id: "mock-nba-m10",
    sport: "nba",
    league: "NBA",
    leagueShort: "NBA",
    homeTeam: n(2),
    awayTeam: n(5),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T03:00:00Z`,
    events: [],
    venue: "Chase Center",
    source: "mock",
    sportDetail: { homeRecord: "28-28", awayRecord: "29-27" },
  },
];

// ═══════════════════════════════════════════════════════════════
// NFL MATCHES
// ═══════════════════════════════════════════════════════════════

function nflDetail(
  home: number[],
  away: number[],
  homeRec: string,
  awayRec: string,
  situation?: SportDetail["situation"],
  leaders?: SportDetail["leaders"]
): SportDetail {
  return { linescores: { home, away }, homeRecord: homeRec, awayRecord: awayRec, situation, leaders };
}

export const nflMatches: Match[] = [
  // --- FINISHED ---
  {
    id: "mock-nfl-m1",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(0),
    awayTeam: f(1),
    homeScore: 31,
    awayScore: 24,
    status: "finished",
    startTime: `${twoDaysAgo}T18:25:00Z`,
    events: [],
    venue: "GEHA Field at Arrowhead Stadium",
    source: "mock",
    sportDetail: nflDetail([7, 10, 7, 7], [3, 14, 0, 7], "13-4", "12-5", undefined, [
      { category: "Passing", playerName: "Patrick Mahomes", displayValue: "312 YDS, 3 TD", teamSide: "home" },
      { category: "Rushing", playerName: "Christian McCaffrey", displayValue: "98 YDS, 1 TD", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nfl-m2",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(2),
    awayTeam: f(3),
    homeScore: 28,
    awayScore: 17,
    status: "finished",
    startTime: `${twoDaysAgo}T21:20:00Z`,
    events: [],
    venue: "Lincoln Financial Field",
    source: "mock",
    sportDetail: nflDetail([7, 14, 0, 7], [3, 7, 7, 0], "11-6", "10-7", undefined, [
      { category: "Passing", playerName: "Jalen Hurts", displayValue: "275 YDS, 2 TD", teamSide: "home" },
      { category: "Rushing", playerName: "Saquon Barkley", displayValue: "132 YDS, 1 TD", teamSide: "home" },
      { category: "Receiving", playerName: "CeeDee Lamb", displayValue: "9 REC, 112 YDS", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nfl-m3",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(5),
    awayTeam: f(4),
    homeScore: 34,
    awayScore: 27,
    status: "finished",
    startTime: `${yesterday}T18:00:00Z`,
    events: [],
    venue: "M&T Bank Stadium",
    source: "mock",
    sportDetail: nflDetail([7, 10, 10, 7], [7, 7, 6, 7], "13-4", "11-6", undefined, [
      { category: "Passing", playerName: "Lamar Jackson", displayValue: "290 YDS, 2 TD", teamSide: "home" },
      { category: "Rushing", playerName: "Derrick Henry", displayValue: "145 YDS, 2 TD", teamSide: "home" },
      { category: "Passing", playerName: "Josh Allen", displayValue: "305 YDS, 3 TD", teamSide: "away" },
    ]),
  },
  {
    id: "mock-nfl-m4",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(6),
    awayTeam: f(7),
    homeScore: 42,
    awayScore: 35,
    status: "finished",
    startTime: `${yesterday}T21:15:00Z`,
    events: [],
    venue: "Ford Field",
    source: "mock",
    sportDetail: nflDetail([14, 7, 14, 7], [7, 14, 7, 7], "12-5", "11-6", undefined, [
      { category: "Passing", playerName: "Jared Goff", displayValue: "340 YDS, 4 TD", teamSide: "home" },
      { category: "Receiving", playerName: "Amon-Ra St. Brown", displayValue: "11 REC, 148 YDS, 2 TD", teamSide: "home" },
      { category: "Passing", playerName: "Tua Tagovailoa", displayValue: "310 YDS, 3 TD", teamSide: "away" },
    ]),
  },
  // --- LIVE ---
  {
    id: "mock-nfl-m5",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(0),
    awayTeam: f(5),
    homeScore: 21,
    awayScore: 14,
    status: "live",
    clock: { value: 3, displayValue: "Q3 8:45" },
    startTime: `${today}T18:25:00Z`,
    events: [],
    venue: "GEHA Field at Arrowhead Stadium",
    source: "mock",
    sportDetail: nflDetail([7, 7, 7], [7, 7, 0], "13-4", "13-4", {
      down: 2,
      distance: 7,
      yardLine: 35,
      possession: "home",
      lastPlay: "Pacheco rushes for 3 yards",
      isRedZone: false,
    }),
  },
  // --- UPCOMING ---
  {
    id: "mock-nfl-m6",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(1),
    awayTeam: f(2),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T18:00:00Z`,
    events: [],
    venue: "Levi's Stadium",
    source: "mock",
    sportDetail: { homeRecord: "12-5", awayRecord: "11-6" },
  },
  {
    id: "mock-nfl-m7",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(3),
    awayTeam: f(6),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T21:20:00Z`,
    events: [],
    venue: "AT&T Stadium",
    source: "mock",
    sportDetail: { homeRecord: "10-7", awayRecord: "12-5" },
  },
  {
    id: "mock-nfl-m8",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(4),
    awayTeam: f(7),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T18:00:00Z`,
    events: [],
    venue: "Highmark Stadium",
    source: "mock",
    sportDetail: { homeRecord: "11-6", awayRecord: "11-6" },
  },
  {
    id: "mock-nfl-m9",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(2),
    awayTeam: f(0),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T01:00:00Z`,
    events: [],
    venue: "Lincoln Financial Field",
    source: "mock",
    sportDetail: { homeRecord: "11-6", awayRecord: "13-4" },
  },
  {
    id: "mock-nfl-m10",
    sport: "nfl",
    league: "National Football League",
    leagueShort: "NFL",
    homeTeam: f(7),
    awayTeam: f(1),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T18:00:00Z`,
    events: [],
    venue: "Hard Rock Stadium",
    source: "mock",
    sportDetail: { homeRecord: "11-6", awayRecord: "12-5" },
  },
];

// ═══════════════════════════════════════════════════════════════
// NHL MATCHES
// ═══════════════════════════════════════════════════════════════

function nhlDetail(
  home: number[],
  away: number[],
  homeRec: string,
  awayRec: string
): SportDetail {
  return { linescores: { home, away }, homeRecord: homeRec, awayRecord: awayRec };
}

export const nhlMatches: Match[] = [
  // --- FINISHED ---
  {
    id: "mock-nhl-m1",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(0),
    awayTeam: h(1),
    homeScore: 4,
    awayScore: 3,
    status: "finished",
    startTime: `${twoDaysAgo}T01:00:00Z`,
    events: [],
    venue: "Rogers Place",
    source: "mock",
    sportDetail: nhlDetail([1, 2, 1], [1, 1, 1], "35-18-4", "37-16-5"),
  },
  {
    id: "mock-nhl-m2",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(2),
    awayTeam: h(3),
    homeScore: 2,
    awayScore: 5,
    status: "finished",
    startTime: `${twoDaysAgo}T02:00:00Z`,
    events: [],
    venue: "American Airlines Center",
    source: "mock",
    sportDetail: nhlDetail([1, 0, 1], [2, 1, 2], "33-20-5", "36-17-4"),
  },
  {
    id: "mock-nhl-m3",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(4),
    awayTeam: h(5),
    homeScore: 3,
    awayScore: 1,
    status: "finished",
    startTime: `${yesterday}T00:00:00Z`,
    events: [],
    venue: "Madison Square Garden",
    source: "mock",
    sportDetail: nhlDetail([1, 1, 1], [0, 0, 1], "34-19-4", "32-21-5"),
  },
  {
    id: "mock-nhl-m4",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(6),
    awayTeam: h(7),
    homeScore: 5,
    awayScore: 4,
    status: "finished",
    startTime: `${yesterday}T00:00:00Z`,
    events: [],
    venue: "TD Garden",
    source: "mock",
    sportDetail: nhlDetail([2, 1, 2], [1, 2, 1], "30-22-6", "35-18-5"),
  },
  // --- LIVE ---
  {
    id: "mock-nhl-m5",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(0),
    awayTeam: h(3),
    homeScore: 2,
    awayScore: 1,
    status: "live",
    clock: { value: 2, displayValue: "P2 10:15" },
    startTime: `${today}T01:00:00Z`,
    events: [],
    venue: "Rogers Place",
    source: "mock",
    sportDetail: nhlDetail([1, 1], [0, 1], "35-18-4", "36-17-4"),
  },
  {
    id: "mock-nhl-m6",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(1),
    awayTeam: h(6),
    homeScore: 3,
    awayScore: 3,
    status: "live",
    clock: { value: 3, displayValue: "P3 4:30" },
    startTime: `${today}T00:00:00Z`,
    events: [],
    venue: "Amerant Bank Arena",
    source: "mock",
    sportDetail: nhlDetail([1, 1, 1], [1, 1, 1], "37-16-5", "30-22-6"),
  },
  // --- UPCOMING ---
  {
    id: "mock-nhl-m7",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(5),
    awayTeam: h(2),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T00:00:00Z`,
    events: [],
    venue: "PNC Arena",
    source: "mock",
    sportDetail: { homeRecord: "32-21-5", awayRecord: "33-20-5" },
  },
  {
    id: "mock-nhl-m8",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(7),
    awayTeam: h(4),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T03:00:00Z`,
    events: [],
    venue: "T-Mobile Arena",
    source: "mock",
    sportDetail: { homeRecord: "35-18-5", awayRecord: "36-17-4" },
  },
  {
    id: "mock-nhl-m9",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(3),
    awayTeam: h(0),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T02:00:00Z`,
    events: [],
    venue: "Ball Arena",
    source: "mock",
    sportDetail: { homeRecord: "36-17-4", awayRecord: "35-18-4" },
  },
  {
    id: "mock-nhl-m10",
    sport: "nhl",
    league: "National Hockey League",
    leagueShort: "NHL",
    homeTeam: h(2),
    awayTeam: h(1),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T01:00:00Z`,
    events: [],
    venue: "American Airlines Center",
    source: "mock",
    sportDetail: { homeRecord: "33-20-5", awayRecord: "37-16-5" },
  },
];

// ═══════════════════════════════════════════════════════════════
// MLB MATCHES
// ═══════════════════════════════════════════════════════════════

function mlbDetail(
  home: number[],
  away: number[],
  homeRec: string,
  awayRec: string
): SportDetail {
  return { linescores: { home, away }, homeRecord: homeRec, awayRecord: awayRec };
}

export const mlbMatches: Match[] = [
  // --- FINISHED ---
  {
    id: "mock-mlb-m1",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(0),
    awayTeam: b(1),
    homeScore: 7,
    awayScore: 4,
    status: "finished",
    startTime: `${twoDaysAgo}T01:10:00Z`,
    events: [],
    venue: "Dodger Stadium",
    source: "mock",
    sportDetail: mlbDetail([0, 2, 0, 1, 0, 3, 0, 1, 0], [1, 0, 0, 2, 0, 0, 1, 0, 0], "62-38", "55-45"),
  },
  {
    id: "mock-mlb-m2",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(3),
    awayTeam: b(2),
    homeScore: 5,
    awayScore: 3,
    status: "finished",
    startTime: `${twoDaysAgo}T23:05:00Z`,
    events: [],
    venue: "Yankee Stadium",
    source: "mock",
    sportDetail: mlbDetail([1, 0, 2, 0, 0, 1, 0, 1, 0], [0, 1, 0, 0, 2, 0, 0, 0, 0], "58-42", "56-44"),
  },
  {
    id: "mock-mlb-m3",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(4),
    awayTeam: b(5),
    homeScore: 3,
    awayScore: 2,
    status: "finished",
    startTime: `${yesterday}T23:05:00Z`,
    events: [],
    venue: "Citizens Bank Park",
    source: "mock",
    sportDetail: mlbDetail([0, 0, 1, 0, 0, 0, 2, 0, 0], [0, 1, 0, 0, 0, 1, 0, 0, 0], "57-43", "52-48"),
  },
  {
    id: "mock-mlb-m4",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(6),
    awayTeam: b(7),
    homeScore: 8,
    awayScore: 2,
    status: "finished",
    startTime: `${yesterday}T23:35:00Z`,
    events: [],
    venue: "Oriole Park at Camden Yards",
    source: "mock",
    sportDetail: mlbDetail([2, 0, 3, 0, 1, 0, 2, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0], "54-46", "48-52"),
  },
  // --- LIVE ---
  {
    id: "mock-mlb-m5",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(0),
    awayTeam: b(3),
    homeScore: 3,
    awayScore: 2,
    status: "live",
    clock: { value: 6, displayValue: "Bot 6th" },
    startTime: `${today}T01:10:00Z`,
    events: [],
    venue: "Dodger Stadium",
    source: "mock",
    sportDetail: mlbDetail([0, 1, 0, 0, 2, 0], [1, 0, 0, 1, 0, 0], "62-38", "58-42"),
  },
  {
    id: "mock-mlb-m6",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(2),
    awayTeam: b(1),
    homeScore: 4,
    awayScore: 4,
    status: "live",
    clock: { value: 7, displayValue: "Top 7th" },
    startTime: `${today}T00:05:00Z`,
    events: [],
    venue: "Minute Maid Park",
    source: "mock",
    sportDetail: mlbDetail([0, 2, 0, 1, 0, 1, 0], [1, 0, 0, 2, 0, 0, 1], "56-44", "55-45"),
  },
  // --- UPCOMING ---
  {
    id: "mock-mlb-m7",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(1),
    awayTeam: b(4),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T23:20:00Z`,
    events: [],
    venue: "Truist Park",
    source: "mock",
    sportDetail: { homeRecord: "55-45", awayRecord: "57-43" },
  },
  {
    id: "mock-mlb-m8",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(5),
    awayTeam: b(6),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${tomorrow}T00:05:00Z`,
    events: [],
    venue: "Globe Life Field",
    source: "mock",
    sportDetail: { homeRecord: "52-48", awayRecord: "54-46" },
  },
  {
    id: "mock-mlb-m9",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(7),
    awayTeam: b(0),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T23:10:00Z`,
    events: [],
    venue: "Tropicana Field",
    source: "mock",
    sportDetail: { homeRecord: "48-52", awayRecord: "62-38" },
  },
  {
    id: "mock-mlb-m10",
    sport: "mlb",
    league: "Major League Baseball",
    leagueShort: "MLB",
    homeTeam: b(3),
    awayTeam: b(4),
    homeScore: null,
    awayScore: null,
    status: "upcoming",
    startTime: `${dayAfter}T23:05:00Z`,
    events: [],
    venue: "Yankee Stadium",
    source: "mock",
    sportDetail: { homeRecord: "58-42", awayRecord: "57-43" },
  },
];

// ═══════════════════════════════════════════════════════════════
// ALL MATCHES — lookup helpers
// ═══════════════════════════════════════════════════════════════

export const allMockMatches: Match[] = [
  ...soccerMatches,
  ...multiLeagueSoccerMatches,
  ...nbaMatches,
  ...nflMatches,
  ...nhlMatches,
  ...mlbMatches,
];

export function getMatchesForSport(sport: Sport): Match[] {
  switch (sport) {
    case "soccer": return [...soccerMatches, ...multiLeagueSoccerMatches];
    case "nba": return nbaMatches;
    case "nfl": return nflMatches;
    case "nhl": return nhlMatches;
    case "mlb": return mlbMatches;
  }
}

export function getMatchById(id: string): Match | undefined {
  return allMockMatches.find((m) => m.id === id);
}
