import type { Team, Sport } from "../types";

export interface MockSquadPlayer {
  id: string;
  name: string;
  position: string;
  shirtNumber: number | null;
  nationality?: string;
}

export interface MockTeamData {
  team: Team;
  venue: string;
  coach: string;
  founded: number;
  squad: MockSquadPlayer[];
}

function badge(abbr: string): string {
  return `https://placehold.co/64x64/1E1B3A/7EB6E6?text=${abbr}`;
}

function makeTeam(id: string, name: string, shortName: string, sport: Sport): Team {
  return { id, name, shortName, badge: badge(shortName), sport };
}

function makeSquad(
  teamId: string,
  players: [string, string, number | null, string?][]
): MockSquadPlayer[] {
  return players.map(([name, position, jersey, nationality], i) => ({
    id: `${teamId}-p${i + 1}`,
    name,
    position,
    shirtNumber: jersey,
    nationality,
  }));
}

// ═══════════════════════════════════════════════════════════════
// SOCCER — Premier League
// ═══════════════════════════════════════════════════════════════

export const soccerTeams: MockTeamData[] = [
  {
    team: makeTeam("mock-soccer-1", "Arsenal", "ARS", "soccer"),
    venue: "Emirates Stadium",
    coach: "Mikel Arteta",
    founded: 1886,
    squad: makeSquad("mock-soccer-1", [
      ["David Raya", "Goalkeeper", 1, "Spain"],
      ["Ben White", "Defence", 4, "England"],
      ["William Saliba", "Defence", 2, "France"],
      ["Gabriel Magalhães", "Defence", 6, "Brazil"],
      ["Oleksandr Zinchenko", "Defence", 35, "Ukraine"],
      ["Jurriën Timber", "Defence", 12, "Netherlands"],
      ["Declan Rice", "Midfield", 41, "England"],
      ["Martin Ødegaard", "Midfield", 8, "Norway"],
      ["Jorginho", "Midfield", 20, "Italy"],
      ["Thomas Partey", "Midfield", 5, "Ghana"],
      ["Bukayo Saka", "Offence", 7, "England"],
      ["Kai Havertz", "Offence", 29, "Germany"],
      ["Leandro Trossard", "Offence", 19, "Belgium"],
      ["Gabriel Martinelli", "Offence", 11, "Brazil"],
      ["Gabriel Jesus", "Offence", 9, "Brazil"],
      ["Aaron Ramsdale", "Goalkeeper", 18, "England"],
      ["Eddie Nketiah", "Offence", 14, "England"],
      ["Jakub Kiwior", "Defence", 15, "Poland"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-2", "Manchester City", "MCI", "soccer"),
    venue: "Etihad Stadium",
    coach: "Pep Guardiola",
    founded: 1880,
    squad: makeSquad("mock-soccer-2", [
      ["Ederson", "Goalkeeper", 31, "Brazil"],
      ["Kyle Walker", "Defence", 2, "England"],
      ["Rúben Dias", "Defence", 3, "Portugal"],
      ["Manuel Akanji", "Defence", 25, "Switzerland"],
      ["Joško Gvardiol", "Defence", 24, "Croatia"],
      ["John Stones", "Defence", 5, "England"],
      ["Rodri", "Midfield", 16, "Spain"],
      ["Kevin De Bruyne", "Midfield", 17, "Belgium"],
      ["Bernardo Silva", "Midfield", 20, "Portugal"],
      ["Mateo Kovačić", "Midfield", 8, "Croatia"],
      ["Phil Foden", "Offence", 47, "England"],
      ["Erling Haaland", "Offence", 9, "Norway"],
      ["Jack Grealish", "Offence", 10, "England"],
      ["Jérémy Doku", "Offence", 11, "Belgium"],
      ["Julián Álvarez", "Offence", 19, "Argentina"],
      ["Stefan Ortega", "Goalkeeper", 18, "Germany"],
      ["Rico Lewis", "Defence", 82, "England"],
      ["Matheus Nunes", "Midfield", 27, "Portugal"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-3", "Liverpool", "LIV", "soccer"),
    venue: "Anfield",
    coach: "Arne Slot",
    founded: 1892,
    squad: makeSquad("mock-soccer-3", [
      ["Alisson Becker", "Goalkeeper", 1, "Brazil"],
      ["Trent Alexander-Arnold", "Defence", 66, "England"],
      ["Virgil van Dijk", "Defence", 4, "Netherlands"],
      ["Ibrahima Konaté", "Defence", 5, "France"],
      ["Andrew Robertson", "Defence", 26, "Scotland"],
      ["Joe Gomez", "Defence", 2, "England"],
      ["Alexis Mac Allister", "Midfield", 10, "Argentina"],
      ["Dominik Szoboszlai", "Midfield", 8, "Hungary"],
      ["Ryan Gravenberch", "Midfield", 38, "Netherlands"],
      ["Curtis Jones", "Midfield", 17, "England"],
      ["Harvey Elliott", "Midfield", 19, "England"],
      ["Mohamed Salah", "Offence", 11, "Egypt"],
      ["Darwin Núñez", "Offence", 9, "Uruguay"],
      ["Luis Díaz", "Offence", 7, "Colombia"],
      ["Cody Gakpo", "Offence", 18, "Netherlands"],
      ["Diogo Jota", "Offence", 20, "Portugal"],
      ["Caoimhín Kelleher", "Goalkeeper", 62, "Ireland"],
      ["Wataru Endo", "Midfield", 3, "Japan"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-4", "Chelsea", "CHE", "soccer"),
    venue: "Stamford Bridge",
    coach: "Enzo Maresca",
    founded: 1905,
    squad: makeSquad("mock-soccer-4", [
      ["Robert Sánchez", "Goalkeeper", 1, "Spain"],
      ["Reece James", "Defence", 24, "England"],
      ["Levi Colwill", "Defence", 6, "England"],
      ["Marc Cucurella", "Defence", 3, "Spain"],
      ["Malo Gusto", "Defence", 27, "France"],
      ["Wesley Fofana", "Defence", 33, "France"],
      ["Moisés Caicedo", "Midfield", 25, "Ecuador"],
      ["Enzo Fernández", "Midfield", 8, "Argentina"],
      ["Conor Gallagher", "Midfield", 23, "England"],
      ["Romeo Lavia", "Midfield", 45, "Belgium"],
      ["Cole Palmer", "Offence", 20, "England"],
      ["Raheem Sterling", "Offence", 17, "England"],
      ["Nicolas Jackson", "Offence", 15, "Senegal"],
      ["Mykhailo Mudryk", "Offence", 10, "Ukraine"],
      ["Noni Madueke", "Offence", 11, "England"],
      ["Christopher Nkunku", "Offence", 18, "France"],
      ["Đorđe Petrović", "Goalkeeper", 28, "Serbia"],
      ["Benoît Badiashile", "Defence", 4, "France"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-5", "Manchester United", "MUN", "soccer"),
    venue: "Old Trafford",
    coach: "Rúben Amorim",
    founded: 1878,
    squad: makeSquad("mock-soccer-5", [
      ["André Onana", "Goalkeeper", 24, "Cameroon"],
      ["Diogo Dalot", "Defence", 20, "Portugal"],
      ["Raphaël Varane", "Defence", 19, "France"],
      ["Lisandro Martínez", "Defence", 6, "Argentina"],
      ["Luke Shaw", "Defence", 23, "England"],
      ["Harry Maguire", "Defence", 5, "England"],
      ["Casemiro", "Midfield", 18, "Brazil"],
      ["Bruno Fernandes", "Midfield", 8, "Portugal"],
      ["Kobbie Mainoo", "Midfield", 37, "England"],
      ["Christian Eriksen", "Midfield", 14, "Denmark"],
      ["Mason Mount", "Midfield", 7, "England"],
      ["Marcus Rashford", "Offence", 10, "England"],
      ["Rasmus Højlund", "Offence", 11, "Denmark"],
      ["Alejandro Garnacho", "Offence", 17, "Argentina"],
      ["Antony", "Offence", 21, "Brazil"],
      ["Altay Bayındır", "Goalkeeper", 1, "Turkey"],
      ["Scott McTominay", "Midfield", 39, "Scotland"],
      ["Victor Lindelöf", "Defence", 2, "Sweden"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-6", "Tottenham Hotspur", "TOT", "soccer"),
    venue: "Tottenham Hotspur Stadium",
    coach: "Ange Postecoglou",
    founded: 1882,
    squad: makeSquad("mock-soccer-6", [
      ["Guglielmo Vicario", "Goalkeeper", 13, "Italy"],
      ["Pedro Porro", "Defence", 23, "Spain"],
      ["Cristian Romero", "Defence", 17, "Argentina"],
      ["Micky van de Ven", "Defence", 37, "Netherlands"],
      ["Destiny Udogie", "Defence", 13, "Italy"],
      ["Emerson Royal", "Defence", 12, "Brazil"],
      ["Yves Bissouma", "Midfield", 38, "Mali"],
      ["James Maddison", "Midfield", 10, "England"],
      ["Pape Matar Sarr", "Midfield", 29, "Senegal"],
      ["Rodrigo Bentancur", "Midfield", 30, "Uruguay"],
      ["Oliver Skipp", "Midfield", 4, "England"],
      ["Son Heung-min", "Offence", 7, "South Korea"],
      ["Richarlison", "Offence", 9, "Brazil"],
      ["Brennan Johnson", "Offence", 22, "Wales"],
      ["Dejan Kulusevski", "Offence", 21, "Sweden"],
      ["Timo Werner", "Offence", 16, "Germany"],
      ["Fraser Forster", "Goalkeeper", 20, "England"],
      ["Giovani Lo Celso", "Midfield", 18, "Argentina"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-7", "Newcastle United", "NEW", "soccer"),
    venue: "St James' Park",
    coach: "Eddie Howe",
    founded: 1892,
    squad: makeSquad("mock-soccer-7", [
      ["Nick Pope", "Goalkeeper", 22, "England"],
      ["Kieran Trippier", "Defence", 2, "England"],
      ["Sven Botman", "Defence", 4, "Netherlands"],
      ["Fabian Schär", "Defence", 5, "Switzerland"],
      ["Dan Burn", "Defence", 33, "England"],
      ["Jamaal Lascelles", "Defence", 6, "England"],
      ["Bruno Guimarães", "Midfield", 39, "Brazil"],
      ["Sandro Tonali", "Midfield", 8, "Italy"],
      ["Joelinton", "Midfield", 7, "Brazil"],
      ["Sean Longstaff", "Midfield", 36, "England"],
      ["Joe Willock", "Midfield", 28, "England"],
      ["Alexander Isak", "Offence", 14, "Sweden"],
      ["Anthony Gordon", "Offence", 10, "England"],
      ["Callum Wilson", "Offence", 9, "England"],
      ["Harvey Barnes", "Offence", 11, "England"],
      ["Jacob Murphy", "Offence", 23, "England"],
      ["Miguel Almirón", "Offence", 24, "Paraguay"],
      ["Martin Dúbravka", "Goalkeeper", 12, "Slovakia"],
    ]),
  },
  {
    team: makeTeam("mock-soccer-8", "Aston Villa", "AVL", "soccer"),
    venue: "Villa Park",
    coach: "Unai Emery",
    founded: 1874,
    squad: makeSquad("mock-soccer-8", [
      ["Emiliano Martínez", "Goalkeeper", 1, "Argentina"],
      ["Matty Cash", "Defence", 2, "Poland"],
      ["Ezri Konsa", "Defence", 4, "England"],
      ["Pau Torres", "Defence", 14, "Spain"],
      ["Lucas Digne", "Defence", 12, "France"],
      ["Tyrone Mings", "Defence", 40, "England"],
      ["Boubacar Kamara", "Midfield", 44, "France"],
      ["John McGinn", "Midfield", 7, "Scotland"],
      ["Douglas Luiz", "Midfield", 6, "Brazil"],
      ["Youri Tielemans", "Midfield", 8, "Belgium"],
      ["Jacob Ramsey", "Midfield", 41, "England"],
      ["Ollie Watkins", "Offence", 11, "England"],
      ["Leon Bailey", "Offence", 31, "Jamaica"],
      ["Moussa Diaby", "Offence", 19, "France"],
      ["Emiliano Buendía", "Offence", 10, "Argentina"],
      ["Jhon Durán", "Offence", 9, "Colombia"],
      ["Robin Olsen", "Goalkeeper", 33, "Sweden"],
      ["Leander Dendoncker", "Midfield", 32, "Belgium"],
    ]),
  },
];

// ═══════════════════════════════════════════════════════════════
// NBA
// ═══════════════════════════════════════════════════════════════

export const nbaTeams: MockTeamData[] = [
  {
    team: makeTeam("mock-nba-1", "Los Angeles Lakers", "LAL", "nba"),
    venue: "Crypto.com Arena",
    coach: "JJ Redick",
    founded: 1947,
    squad: makeSquad("mock-nba-1", [
      ["LeBron James", "Forward", 23],
      ["Anthony Davis", "Forward-Center", 3],
      ["D'Angelo Russell", "Guard", 1],
      ["Austin Reaves", "Guard", 15],
      ["Rui Hachimura", "Forward", 28],
      ["Jarred Vanderbilt", "Forward", 2],
      ["Gabe Vincent", "Guard", 7],
      ["Cam Reddish", "Forward", 5],
      ["Taurean Prince", "Forward", 12],
      ["Spencer Dinwiddie", "Guard", 26],
      ["Jaxson Hayes", "Center", 11],
      ["Christian Wood", "Forward-Center", 35],
      ["Max Christie", "Guard", 10],
      ["D'Moi Hodge", "Guard", 14],
      ["Jalen Hood-Schifino", "Guard", 0],
    ]),
  },
  {
    team: makeTeam("mock-nba-2", "Boston Celtics", "BOS", "nba"),
    venue: "TD Garden",
    coach: "Joe Mazzulla",
    founded: 1946,
    squad: makeSquad("mock-nba-2", [
      ["Jayson Tatum", "Forward", 0],
      ["Jaylen Brown", "Guard-Forward", 7],
      ["Jrue Holiday", "Guard", 4],
      ["Kristaps Porziņģis", "Center", 8],
      ["Derrick White", "Guard", 9],
      ["Al Horford", "Center", 42],
      ["Payton Pritchard", "Guard", 11],
      ["Sam Hauser", "Forward", 30],
      ["Luke Kornet", "Center", 40],
      ["Oshae Brissett", "Forward", 12],
      ["Jaden Springer", "Guard", 23],
      ["Lamar Stevens", "Forward", 15],
      ["Svi Mykhailiuk", "Guard", 19],
      ["Xavier Tillman", "Forward-Center", 26],
      ["Dalano Banton", "Guard", 45],
    ]),
  },
  {
    team: makeTeam("mock-nba-3", "Golden State Warriors", "GSW", "nba"),
    venue: "Chase Center",
    coach: "Steve Kerr",
    founded: 1946,
    squad: makeSquad("mock-nba-3", [
      ["Stephen Curry", "Guard", 30],
      ["Klay Thompson", "Guard", 11],
      ["Draymond Green", "Forward", 23],
      ["Andrew Wiggins", "Forward", 22],
      ["Chris Paul", "Guard", 3],
      ["Kevon Looney", "Center", 5],
      ["Jonathan Kuminga", "Forward", 0],
      ["Moses Moody", "Guard", 4],
      ["Gary Payton II", "Guard", 8],
      ["Brandin Podziemski", "Guard", 2],
      ["Trayce Jackson-Davis", "Forward-Center", 32],
      ["Cory Joseph", "Guard", 14],
      ["Dario Šarić", "Forward-Center", 20],
      ["Lester Quiñones", "Guard", 25],
      ["Pat Spencer", "Guard", 61],
    ]),
  },
  {
    team: makeTeam("mock-nba-4", "Milwaukee Bucks", "MIL", "nba"),
    venue: "Fiserv Forum",
    coach: "Doc Rivers",
    founded: 1968,
    squad: makeSquad("mock-nba-4", [
      ["Giannis Antetokounmpo", "Forward", 34],
      ["Damian Lillard", "Guard", 0],
      ["Khris Middleton", "Forward", 22],
      ["Brook Lopez", "Center", 11],
      ["Bobby Portis", "Forward-Center", 9],
      ["Pat Connaughton", "Guard", 24],
      ["MarJon Beauchamp", "Guard", 3],
      ["Malik Beasley", "Guard", 5],
      ["Cameron Payne", "Guard", 15],
      ["Robin Lopez", "Center", 42],
      ["AJ Green", "Guard", 20],
      ["Thanasis Antetokounmpo", "Forward", 43],
      ["Andre Jackson Jr.", "Guard-Forward", 44],
      ["TyTy Washington", "Guard", 2],
      ["Jae Crowder", "Forward", 99],
    ]),
  },
  {
    team: makeTeam("mock-nba-5", "Denver Nuggets", "DEN", "nba"),
    venue: "Ball Arena",
    coach: "Michael Malone",
    founded: 1967,
    squad: makeSquad("mock-nba-5", [
      ["Nikola Jokić", "Center", 15],
      ["Jamal Murray", "Guard", 27],
      ["Michael Porter Jr.", "Forward", 1],
      ["Aaron Gordon", "Forward", 50],
      ["Kentavious Caldwell-Pope", "Guard", 5],
      ["Reggie Jackson", "Guard", 7],
      ["Christian Braun", "Guard", 0],
      ["Peyton Watson", "Forward", 8],
      ["Zeke Nnaji", "Forward-Center", 22],
      ["DeAndre Jordan", "Center", 6],
      ["Vlatko Čančar", "Forward", 10],
      ["Collin Gillespie", "Guard", 14],
      ["Hunter Tyson", "Forward", 4],
      ["Julian Strawther", "Guard", 2],
      ["Jay Huff", "Center", 30],
    ]),
  },
  {
    team: makeTeam("mock-nba-6", "Philadelphia 76ers", "PHI", "nba"),
    venue: "Wells Fargo Center",
    coach: "Nick Nurse",
    founded: 1946,
    squad: makeSquad("mock-nba-6", [
      ["Joel Embiid", "Center", 21],
      ["Tyrese Maxey", "Guard", 0],
      ["Tobias Harris", "Forward", 12],
      ["Kelly Oubre Jr.", "Forward", 9],
      ["Buddy Hield", "Guard", 17],
      ["De'Anthony Melton", "Guard", 8],
      ["Nicolas Batum", "Forward", 40],
      ["Paul Reed", "Forward-Center", 44],
      ["Kyle Lowry", "Guard", 7],
      ["Mo Bamba", "Center", 5],
      ["Ricky Council IV", "Guard", 16],
      ["Jeff Dowtin Jr.", "Guard", 11],
      ["KJ Martin", "Forward", 1],
      ["Patrick Beverley", "Guard", 22],
      ["Robert Covington", "Forward", 23],
    ]),
  },
  {
    team: makeTeam("mock-nba-7", "Miami Heat", "MIA", "nba"),
    venue: "Kaseya Center",
    coach: "Erik Spoelstra",
    founded: 1988,
    squad: makeSquad("mock-nba-7", [
      ["Jimmy Butler", "Forward", 22],
      ["Bam Adebayo", "Center", 13],
      ["Tyler Herro", "Guard", 14],
      ["Terry Rozier", "Guard", 2],
      ["Caleb Martin", "Forward", 16],
      ["Duncan Robinson", "Forward", 55],
      ["Haywood Highsmith", "Forward", 24],
      ["Kevin Love", "Forward-Center", 42],
      ["Thomas Bryant", "Center", 31],
      ["Nikola Jović", "Forward", 5],
      ["Jaime Jaquez Jr.", "Guard-Forward", 11],
      ["Josh Richardson", "Guard", 0],
      ["Orlando Robinson", "Center", 25],
      ["Dru Smith", "Guard", 9],
      ["Cole Swider", "Forward", 19],
    ]),
  },
  {
    team: makeTeam("mock-nba-8", "Phoenix Suns", "PHX", "nba"),
    venue: "Footprint Center",
    coach: "Frank Vogel",
    founded: 1968,
    squad: makeSquad("mock-nba-8", [
      ["Kevin Durant", "Forward", 35],
      ["Devin Booker", "Guard", 1],
      ["Bradley Beal", "Guard", 3],
      ["Jusuf Nurkić", "Center", 20],
      ["Eric Gordon", "Guard", 23],
      ["Grayson Allen", "Guard", 10],
      ["Drew Eubanks", "Center", 14],
      ["Nassir Little", "Forward", 2],
      ["Bol Bol", "Center", 11],
      ["Damion Lee", "Guard", 7],
      ["Chimezie Metu", "Forward", 25],
      ["Ish Wainright", "Forward", 12],
      ["Josh Okogie", "Guard-Forward", 31],
      ["Saben Lee", "Guard", 38],
      ["David Roddy", "Forward", 21],
    ]),
  },
];

// ═══════════════════════════════════════════════════════════════
// NFL
// ═══════════════════════════════════════════════════════════════

export const nflTeams: MockTeamData[] = [
  {
    team: makeTeam("mock-nfl-1", "Kansas City Chiefs", "KC", "nfl"),
    venue: "GEHA Field at Arrowhead Stadium",
    coach: "Andy Reid",
    founded: 1960,
    squad: makeSquad("mock-nfl-1", [
      ["Patrick Mahomes", "Quarterback", 15],
      ["Travis Kelce", "Tight End", 87],
      ["Isiah Pacheco", "Running Back", 10],
      ["Rashee Rice", "Wide Receiver", 4],
      ["Xavier Worthy", "Wide Receiver", 1],
      ["Chris Jones", "Defensive Tackle", 95],
      ["Nick Bolton", "Linebacker", 32],
      ["Trent McDuffie", "Cornerback", 21],
      ["L'Jarius Sneed", "Cornerback", 38],
      ["George Karlaftis", "Defensive End", 56],
      ["Joe Thuney", "Offensive Line", 62],
      ["Creed Humphrey", "Offensive Line", 52],
      ["Justin Reid", "Safety", 20],
      ["Harrison Butker", "Kicker", 7],
      ["Tommy Townsend", "Punter", 5],
    ]),
  },
  {
    team: makeTeam("mock-nfl-2", "San Francisco 49ers", "SF", "nfl"),
    venue: "Levi's Stadium",
    coach: "Kyle Shanahan",
    founded: 1946,
    squad: makeSquad("mock-nfl-2", [
      ["Brock Purdy", "Quarterback", 13],
      ["Christian McCaffrey", "Running Back", 23],
      ["Deebo Samuel", "Wide Receiver", 19],
      ["Brandon Aiyuk", "Wide Receiver", 11],
      ["George Kittle", "Tight End", 85],
      ["Nick Bosa", "Defensive End", 97],
      ["Fred Warner", "Linebacker", 54],
      ["Charvarius Ward", "Cornerback", 7],
      ["Javon Hargrave", "Defensive Tackle", 98],
      ["Trent Williams", "Offensive Line", 71],
      ["Dre Greenlaw", "Linebacker", 57],
      ["Talanoa Hufanga", "Safety", 29],
      ["Arik Armstead", "Defensive End", 91],
      ["Deommodore Lenoir", "Cornerback", 2],
      ["Jake Moody", "Kicker", 4],
    ]),
  },
  {
    team: makeTeam("mock-nfl-3", "Philadelphia Eagles", "PHI", "nfl"),
    venue: "Lincoln Financial Field",
    coach: "Nick Sirianni",
    founded: 1933,
    squad: makeSquad("mock-nfl-3", [
      ["Jalen Hurts", "Quarterback", 1],
      ["Saquon Barkley", "Running Back", 26],
      ["A.J. Brown", "Wide Receiver", 11],
      ["DeVonta Smith", "Wide Receiver", 6],
      ["Dallas Goedert", "Tight End", 88],
      ["Haason Reddick", "Defensive End", 7],
      ["Jalen Carter", "Defensive Tackle", 98],
      ["Darius Slay", "Cornerback", 2],
      ["Jason Kelce", "Offensive Line", 62],
      ["Lane Johnson", "Offensive Line", 65],
      ["Jordan Mailata", "Offensive Line", 68],
      ["Josh Sweat", "Defensive End", 94],
      ["Reed Blankenship", "Safety", 32],
      ["James Bradberry", "Cornerback", 24],
      ["Jake Elliott", "Kicker", 4],
    ]),
  },
  {
    team: makeTeam("mock-nfl-4", "Dallas Cowboys", "DAL", "nfl"),
    venue: "AT&T Stadium",
    coach: "Mike McCarthy",
    founded: 1960,
    squad: makeSquad("mock-nfl-4", [
      ["Dak Prescott", "Quarterback", 4],
      ["Tony Pollard", "Running Back", 20],
      ["CeeDee Lamb", "Wide Receiver", 88],
      ["Jake Ferguson", "Tight End", 87],
      ["Brandin Cooks", "Wide Receiver", 3],
      ["Micah Parsons", "Linebacker", 11],
      ["DeMarcus Lawrence", "Defensive End", 90],
      ["Trevon Diggs", "Cornerback", 7],
      ["Zack Martin", "Offensive Line", 70],
      ["Tyler Smith", "Offensive Line", 73],
      ["Osa Odighizuwa", "Defensive Tackle", 97],
      ["Jayron Kearse", "Safety", 27],
      ["Leighton Vander Esch", "Linebacker", 55],
      ["Stephon Gilmore", "Cornerback", 21],
      ["Brandon Aubrey", "Kicker", 17],
    ]),
  },
  {
    team: makeTeam("mock-nfl-5", "Buffalo Bills", "BUF", "nfl"),
    venue: "Highmark Stadium",
    coach: "Sean McDermott",
    founded: 1960,
    squad: makeSquad("mock-nfl-5", [
      ["Josh Allen", "Quarterback", 17],
      ["James Cook", "Running Back", 4],
      ["Stefon Diggs", "Wide Receiver", 14],
      ["Gabe Davis", "Wide Receiver", 13],
      ["Dawson Knox", "Tight End", 88],
      ["Von Miller", "Linebacker", 40],
      ["Matt Milano", "Linebacker", 58],
      ["Tre'Davious White", "Cornerback", 27],
      ["Ed Oliver", "Defensive Tackle", 91],
      ["Dion Dawkins", "Offensive Line", 73],
      ["Jordan Poyer", "Safety", 21],
      ["Micah Hyde", "Safety", 23],
      ["Greg Rousseau", "Defensive End", 50],
      ["A.J. Epenesa", "Defensive End", 57],
      ["Tyler Bass", "Kicker", 2],
    ]),
  },
  {
    team: makeTeam("mock-nfl-6", "Baltimore Ravens", "BAL", "nfl"),
    venue: "M&T Bank Stadium",
    coach: "John Harbaugh",
    founded: 1996,
    squad: makeSquad("mock-nfl-6", [
      ["Lamar Jackson", "Quarterback", 8],
      ["Derrick Henry", "Running Back", 22],
      ["Zay Flowers", "Wide Receiver", 4],
      ["Mark Andrews", "Tight End", 89],
      ["Odell Beckham Jr.", "Wide Receiver", 3],
      ["Roquan Smith", "Linebacker", 0],
      ["Kyle Hamilton", "Safety", 14],
      ["Marlon Humphrey", "Cornerback", 44],
      ["Justin Madubuike", "Defensive Tackle", 92],
      ["Ronnie Stanley", "Offensive Line", 79],
      ["Tyler Linderbaum", "Offensive Line", 64],
      ["Patrick Queen", "Linebacker", 6],
      ["Brandon Stephens", "Cornerback", 21],
      ["Jadeveon Clowney", "Defensive End", 24],
      ["Justin Tucker", "Kicker", 9],
    ]),
  },
  {
    team: makeTeam("mock-nfl-7", "Detroit Lions", "DET", "nfl"),
    venue: "Ford Field",
    coach: "Dan Campbell",
    founded: 1930,
    squad: makeSquad("mock-nfl-7", [
      ["Jared Goff", "Quarterback", 16],
      ["Jahmyr Gibbs", "Running Back", 26],
      ["Amon-Ra St. Brown", "Wide Receiver", 14],
      ["Sam LaPorta", "Tight End", 87],
      ["Josh Reynolds", "Wide Receiver", 8],
      ["Aidan Hutchinson", "Defensive End", 97],
      ["Penei Sewell", "Offensive Line", 58],
      ["Frank Ragnow", "Offensive Line", 77],
      ["Alex Anzalone", "Linebacker", 34],
      ["Kerby Joseph", "Safety", 31],
      ["Cameron Sutton", "Cornerback", 1],
      ["DJ Reader", "Defensive Tackle", 98],
      ["Alim McNeill", "Defensive Tackle", 54],
      ["Brian Branch", "Safety", 32],
      ["Michael Badgley", "Kicker", 17],
    ]),
  },
  {
    team: makeTeam("mock-nfl-8", "Miami Dolphins", "MIA", "nfl"),
    venue: "Hard Rock Stadium",
    coach: "Mike McDaniel",
    founded: 1966,
    squad: makeSquad("mock-nfl-8", [
      ["Tua Tagovailoa", "Quarterback", 1],
      ["Raheem Mostert", "Running Back", 31],
      ["Tyreek Hill", "Wide Receiver", 10],
      ["Jaylen Waddle", "Wide Receiver", 17],
      ["Durham Smythe", "Tight End", 81],
      ["Jaelan Phillips", "Linebacker", 15],
      ["Bradley Chubb", "Linebacker", 2],
      ["Xavien Howard", "Cornerback", 25],
      ["Jevon Holland", "Safety", 8],
      ["Terron Armstead", "Offensive Line", 72],
      ["Austin Jackson", "Offensive Line", 73],
      ["Zach Sieler", "Defensive Tackle", 92],
      ["Christian Wilkins", "Defensive Tackle", 94],
      ["Kader Kohou", "Cornerback", 28],
      ["Jason Sanders", "Kicker", 7],
    ]),
  },
];

// ═══════════════════════════════════════════════════════════════
// NHL
// ═══════════════════════════════════════════════════════════════

export const nhlTeams: MockTeamData[] = [
  {
    team: makeTeam("mock-nhl-1", "Edmonton Oilers", "EDM", "nhl"),
    venue: "Rogers Place",
    coach: "Kris Knoblauch",
    founded: 1972,
    squad: makeSquad("mock-nhl-1", [
      ["Connor McDavid", "Center", 97],
      ["Leon Draisaitl", "Center", 29],
      ["Zach Hyman", "Left Wing", 18],
      ["Ryan Nugent-Hopkins", "Center", 93],
      ["Evan Bouchard", "Defenseman", 75],
      ["Darnell Nurse", "Defenseman", 25],
      ["Mattias Ekholm", "Defenseman", 14],
      ["Connor Brown", "Right Wing", 28],
      ["Ryan McLeod", "Center", 71],
      ["Warren Foegele", "Left Wing", 37],
      ["Adam Henrique", "Center", 19],
      ["Brett Kulak", "Defenseman", 27],
      ["Cody Ceci", "Defenseman", 5],
      ["Stuart Skinner", "Goalie", 74],
      ["Jack Campbell", "Goalie", 36],
    ]),
  },
  {
    team: makeTeam("mock-nhl-2", "Florida Panthers", "FLA", "nhl"),
    venue: "Amerant Bank Arena",
    coach: "Paul Maurice",
    founded: 1993,
    squad: makeSquad("mock-nhl-2", [
      ["Aleksander Barkov", "Center", 16],
      ["Sam Reinhart", "Center", 13],
      ["Matthew Tkachuk", "Left Wing", 19],
      ["Carter Verhaeghe", "Left Wing", 23],
      ["Aaron Ekblad", "Defenseman", 5],
      ["Gustav Forsling", "Defenseman", 42],
      ["Brandon Montour", "Defenseman", 62],
      ["Sam Bennett", "Center", 9],
      ["Evan Rodrigues", "Center", 17],
      ["Anthony Duclair", "Left Wing", 10],
      ["Oliver Ekman-Larsson", "Defenseman", 25],
      ["Nick Cousins", "Center", 21],
      ["Kevin Stenlund", "Center", 44],
      ["Sergei Bobrovsky", "Goalie", 72],
      ["Spencer Knight", "Goalie", 30],
    ]),
  },
  {
    team: makeTeam("mock-nhl-3", "Dallas Stars", "DAL", "nhl"),
    venue: "American Airlines Center",
    coach: "Pete DeBoer",
    founded: 1967,
    squad: makeSquad("mock-nhl-3", [
      ["Jason Robertson", "Left Wing", 21],
      ["Roope Hintz", "Center", 24],
      ["Tyler Seguin", "Center", 91],
      ["Jamie Benn", "Left Wing", 14],
      ["Miro Heiskanen", "Defenseman", 4],
      ["Thomas Harley", "Defenseman", 55],
      ["Ryan Suter", "Defenseman", 20],
      ["Joe Pavelski", "Center", 16],
      ["Wyatt Johnston", "Center", 53],
      ["Mason Marchment", "Left Wing", 27],
      ["Matt Duchene", "Center", 95],
      ["Esa Lindell", "Defenseman", 23],
      ["Nils Lundkvist", "Defenseman", 5],
      ["Jake Oettinger", "Goalie", 29],
      ["Scott Wedgewood", "Goalie", 41],
    ]),
  },
  {
    team: makeTeam("mock-nhl-4", "Colorado Avalanche", "COL", "nhl"),
    venue: "Ball Arena",
    coach: "Jared Bednar",
    founded: 1972,
    squad: makeSquad("mock-nhl-4", [
      ["Nathan MacKinnon", "Center", 29],
      ["Mikko Rantanen", "Right Wing", 96],
      ["Cale Makar", "Defenseman", 8],
      ["Gabriel Landeskog", "Left Wing", 92],
      ["Valeri Nichushkin", "Right Wing", 13],
      ["Devon Toews", "Defenseman", 7],
      ["Samuel Girard", "Defenseman", 49],
      ["Josh Manson", "Defenseman", 42],
      ["Ross Colton", "Center", 20],
      ["Jonathan Drouin", "Left Wing", 27],
      ["Miles Wood", "Left Wing", 28],
      ["Logan O'Connor", "Right Wing", 25],
      ["Andrew Cogliano", "Center", 11],
      ["Alexandar Georgiev", "Goalie", 40],
      ["Justus Annunen", "Goalie", 60],
    ]),
  },
  {
    team: makeTeam("mock-nhl-5", "New York Rangers", "NYR", "nhl"),
    venue: "Madison Square Garden",
    coach: "Peter Laviolette",
    founded: 1926,
    squad: makeSquad("mock-nhl-5", [
      ["Artemi Panarin", "Left Wing", 10],
      ["Mika Zibanejad", "Center", 93],
      ["Chris Kreider", "Left Wing", 20],
      ["Adam Fox", "Defenseman", 23],
      ["Vincent Trocheck", "Center", 16],
      ["K'Andre Miller", "Defenseman", 79],
      ["Alexis Lafrenière", "Left Wing", 13],
      ["Kaapo Kakko", "Right Wing", 24],
      ["Jacob Trouba", "Defenseman", 8],
      ["Filip Chytil", "Center", 72],
      ["Barclay Goodrow", "Center", 21],
      ["Ryan Lindgren", "Defenseman", 55],
      ["Will Cuylle", "Left Wing", 50],
      ["Igor Shesterkin", "Goalie", 31],
      ["Jonathan Quick", "Goalie", 32],
    ]),
  },
  {
    team: makeTeam("mock-nhl-6", "Carolina Hurricanes", "CAR", "nhl"),
    venue: "PNC Arena",
    coach: "Rod Brind'Amour",
    founded: 1972,
    squad: makeSquad("mock-nhl-6", [
      ["Sebastian Aho", "Center", 20],
      ["Andrei Svechnikov", "Right Wing", 37],
      ["Jaccob Slavin", "Defenseman", 74],
      ["Brent Burns", "Defenseman", 8],
      ["Jesperi Kotkaniemi", "Center", 82],
      ["Martin Nečas", "Center", 88],
      ["Seth Jarvis", "Right Wing", 24],
      ["Teuvo Teräväinen", "Left Wing", 86],
      ["Jordan Staal", "Center", 11],
      ["Brady Skjei", "Defenseman", 76],
      ["Brett Pesce", "Defenseman", 22],
      ["Jordan Martinook", "Left Wing", 48],
      ["Jesper Fast", "Right Wing", 71],
      ["Frederik Andersen", "Goalie", 31],
      ["Pyotr Kochetkov", "Goalie", 52],
    ]),
  },
  {
    team: makeTeam("mock-nhl-7", "Boston Bruins", "BOS", "nhl"),
    venue: "TD Garden",
    coach: "Jim Montgomery",
    founded: 1924,
    squad: makeSquad("mock-nhl-7", [
      ["David Pastrňák", "Right Wing", 88],
      ["Brad Marchand", "Left Wing", 63],
      ["Charlie McAvoy", "Defenseman", 73],
      ["Pavel Zacha", "Center", 18],
      ["Charlie Coyle", "Center", 13],
      ["Hampus Lindholm", "Defenseman", 27],
      ["Jake DeBrusk", "Left Wing", 74],
      ["Trent Frederic", "Center", 11],
      ["Brandon Carlo", "Defenseman", 25],
      ["Matt Grzelcyk", "Defenseman", 48],
      ["Danton Heinen", "Left Wing", 43],
      ["Jakub Lauko", "Left Wing", 94],
      ["Morgan Geekie", "Center", 39],
      ["Jeremy Swayman", "Goalie", 1],
      ["Linus Ullmark", "Goalie", 35],
    ]),
  },
  {
    team: makeTeam("mock-nhl-8", "Vegas Golden Knights", "VGK", "nhl"),
    venue: "T-Mobile Arena",
    coach: "Bruce Cassidy",
    founded: 2017,
    squad: makeSquad("mock-nhl-8", [
      ["Jack Eichel", "Center", 9],
      ["Mark Stone", "Right Wing", 61],
      ["Jonathan Marchessault", "Right Wing", 81],
      ["Shea Theodore", "Defenseman", 27],
      ["Alex Pietrangelo", "Defenseman", 7],
      ["William Karlsson", "Center", 71],
      ["Chandler Stephenson", "Center", 20],
      ["Reilly Smith", "Right Wing", 19],
      ["Ivan Barbashev", "Left Wing", 49],
      ["Nicolas Hague", "Defenseman", 14],
      ["Brayden McNabb", "Defenseman", 3],
      ["Michael Amadio", "Center", 22],
      ["William Carrier", "Left Wing", 28],
      ["Adin Hill", "Goalie", 33],
      ["Logan Thompson", "Goalie", 36],
    ]),
  },
];

// ═══════════════════════════════════════════════════════════════
// MLB
// ═══════════════════════════════════════════════════════════════

export const mlbTeams: MockTeamData[] = [
  {
    team: makeTeam("mock-mlb-1", "Los Angeles Dodgers", "LAD", "mlb"),
    venue: "Dodger Stadium",
    coach: "Dave Roberts",
    founded: 1883,
    squad: makeSquad("mock-mlb-1", [
      ["Shohei Ohtani", "Designated Hitter", 17],
      ["Mookie Betts", "Shortstop", 50],
      ["Freddie Freeman", "First Baseman", 5],
      ["Max Muncy", "Third Baseman", 13],
      ["Will Smith", "Catcher", 16],
      ["Teoscar Hernández", "Right Fielder", 37],
      ["James Outman", "Center Fielder", 33],
      ["Chris Taylor", "Left Fielder", 3],
      ["Gavin Lux", "Second Baseman", 9],
      ["Walker Buehler", "Pitcher", 21],
      ["Clayton Kershaw", "Pitcher", 22],
      ["Yoshinobu Yamamoto", "Pitcher", 18],
      ["Bobby Miller", "Pitcher", 31],
      ["Evan Phillips", "Pitcher", 59],
      ["Alex Vesia", "Pitcher", 51],
    ]),
  },
  {
    team: makeTeam("mock-mlb-2", "Atlanta Braves", "ATL", "mlb"),
    venue: "Truist Park",
    coach: "Brian Snitker",
    founded: 1871,
    squad: makeSquad("mock-mlb-2", [
      ["Ronald Acuña Jr.", "Right Fielder", 13],
      ["Matt Olson", "First Baseman", 28],
      ["Austin Riley", "Third Baseman", 27],
      ["Ozzie Albies", "Second Baseman", 1],
      ["Michael Harris II", "Center Fielder", 23],
      ["Sean Murphy", "Catcher", 12],
      ["Orlando Arcia", "Shortstop", 11],
      ["Marcell Ozuna", "Designated Hitter", 20],
      ["Eddie Rosario", "Left Fielder", 8],
      ["Max Fried", "Pitcher", 54],
      ["Spencer Strider", "Pitcher", 65],
      ["Charlie Morton", "Pitcher", 50],
      ["Reynaldo López", "Pitcher", 40],
      ["Raisel Iglesias", "Pitcher", 26],
      ["A.J. Minter", "Pitcher", 33],
    ]),
  },
  {
    team: makeTeam("mock-mlb-3", "Houston Astros", "HOU", "mlb"),
    venue: "Minute Maid Park",
    coach: "Joe Espada",
    founded: 1962,
    squad: makeSquad("mock-mlb-3", [
      ["José Altuve", "Second Baseman", 27],
      ["Yordan Alvarez", "Designated Hitter", 44],
      ["Kyle Tucker", "Right Fielder", 30],
      ["Alex Bregman", "Third Baseman", 2],
      ["Jeremy Peña", "Shortstop", 3],
      ["Yainer Díaz", "Catcher", 21],
      ["Chas McCormick", "Center Fielder", 20],
      ["Jon Singleton", "First Baseman", 28],
      ["Jake Meyers", "Left Fielder", 6],
      ["Framber Valdez", "Pitcher", 59],
      ["Cristian Javier", "Pitcher", 53],
      ["Hunter Brown", "Pitcher", 58],
      ["José Urquidy", "Pitcher", 65],
      ["Ryan Pressly", "Pitcher", 55],
      ["Bryan Abreu", "Pitcher", 52],
    ]),
  },
  {
    team: makeTeam("mock-mlb-4", "New York Yankees", "NYY", "mlb"),
    venue: "Yankee Stadium",
    coach: "Aaron Boone",
    founded: 1901,
    squad: makeSquad("mock-mlb-4", [
      ["Aaron Judge", "Right Fielder", 99],
      ["Juan Soto", "Left Fielder", 22],
      ["Giancarlo Stanton", "Designated Hitter", 27],
      ["Gleyber Torres", "Second Baseman", 25],
      ["Anthony Volpe", "Shortstop", 11],
      ["Anthony Rizzo", "First Baseman", 48],
      ["Austin Wells", "Catcher", 28],
      ["Harrison Bader", "Center Fielder", 22],
      ["DJ LeMahieu", "Third Baseman", 26],
      ["Gerrit Cole", "Pitcher", 45],
      ["Carlos Rodón", "Pitcher", 55],
      ["Nestor Cortes", "Pitcher", 65],
      ["Marcus Stroman", "Pitcher", 0],
      ["Clay Holmes", "Pitcher", 35],
      ["Michael King", "Pitcher", 34],
    ]),
  },
  {
    team: makeTeam("mock-mlb-5", "Philadelphia Phillies", "PHI", "mlb"),
    venue: "Citizens Bank Park",
    coach: "Rob Thomson",
    founded: 1883,
    squad: makeSquad("mock-mlb-5", [
      ["Bryce Harper", "First Baseman", 3],
      ["Trea Turner", "Shortstop", 7],
      ["Kyle Schwarber", "Left Fielder", 12],
      ["Alec Bohm", "Third Baseman", 28],
      ["J.T. Realmuto", "Catcher", 10],
      ["Nick Castellanos", "Right Fielder", 8],
      ["Johan Rojas", "Center Fielder", 18],
      ["Bryson Stott", "Second Baseman", 5],
      ["Brandon Marsh", "Designated Hitter", 16],
      ["Zack Wheeler", "Pitcher", 45],
      ["Aaron Nola", "Pitcher", 27],
      ["Ranger Suárez", "Pitcher", 55],
      ["Cristopher Sánchez", "Pitcher", 61],
      ["José Alvarado", "Pitcher", 46],
      ["Jeff Hoffman", "Pitcher", 12],
    ]),
  },
  {
    team: makeTeam("mock-mlb-6", "Texas Rangers", "TEX", "mlb"),
    venue: "Globe Life Field",
    coach: "Bruce Bochy",
    founded: 1961,
    squad: makeSquad("mock-mlb-6", [
      ["Corey Seager", "Shortstop", 5],
      ["Marcus Semien", "Second Baseman", 2],
      ["Adolis García", "Right Fielder", 53],
      ["Nathaniel Lowe", "First Baseman", 30],
      ["Jonah Heim", "Catcher", 28],
      ["Josh Jung", "Third Baseman", 6],
      ["Evan Carter", "Left Fielder", 32],
      ["Leody Taveras", "Center Fielder", 3],
      ["Mitch Garver", "Designated Hitter", 18],
      ["Nathan Eovaldi", "Pitcher", 17],
      ["Jon Gray", "Pitcher", 22],
      ["Andrew Heaney", "Pitcher", 44],
      ["Dane Dunning", "Pitcher", 33],
      ["Josh Sborz", "Pitcher", 66],
      ["Aroldis Chapman", "Pitcher", 45],
    ]),
  },
  {
    team: makeTeam("mock-mlb-7", "Baltimore Orioles", "BAL", "mlb"),
    venue: "Oriole Park at Camden Yards",
    coach: "Brandon Hyde",
    founded: 1894,
    squad: makeSquad("mock-mlb-7", [
      ["Adley Rutschman", "Catcher", 35],
      ["Gunnar Henderson", "Shortstop", 2],
      ["Ryan Mountcastle", "First Baseman", 6],
      ["Cedric Mullins", "Center Fielder", 31],
      ["Jackson Holliday", "Second Baseman", 7],
      ["Anthony Santander", "Right Fielder", 25],
      ["Colton Cowser", "Left Fielder", 17],
      ["Ramón Urías", "Third Baseman", 29],
      ["Ryan O'Hearn", "Designated Hitter", 32],
      ["Corbin Burnes", "Pitcher", 39],
      ["Grayson Rodriguez", "Pitcher", 30],
      ["Kyle Bradish", "Pitcher", 56],
      ["Dean Kremer", "Pitcher", 64],
      ["Yennier Canó", "Pitcher", 47],
      ["Félix Bautista", "Pitcher", 74],
    ]),
  },
  {
    team: makeTeam("mock-mlb-8", "Tampa Bay Rays", "TB", "mlb"),
    venue: "Tropicana Field",
    coach: "Kevin Cash",
    founded: 1998,
    squad: makeSquad("mock-mlb-8", [
      ["Randy Arozarena", "Left Fielder", 56],
      ["Harold Ramírez", "Designated Hitter", 43],
      ["Isaac Paredes", "Third Baseman", 17],
      ["Brandon Lowe", "Second Baseman", 8],
      ["Yandy Díaz", "First Baseman", 2],
      ["Josh Lowe", "Right Fielder", 15],
      ["Jose Siri", "Center Fielder", 22],
      ["René Pinto", "Catcher", 44],
      ["Taylor Walls", "Shortstop", 0],
      ["Shane McClanahan", "Pitcher", 18],
      ["Zach Eflin", "Pitcher", 24],
      ["Tyler Glasnow", "Pitcher", 20],
      ["Jeffrey Springs", "Pitcher", 59],
      ["Pete Fairbanks", "Pitcher", 29],
      ["Jason Adam", "Pitcher", 47],
    ]),
  },
];

// ═══════════════════════════════════════════════════════════════
// ALL TEAMS — flat lookup helpers
// ═══════════════════════════════════════════════════════════════

export const allMockTeams: MockTeamData[] = [
  ...soccerTeams,
  ...nbaTeams,
  ...nflTeams,
  ...nhlTeams,
  ...mlbTeams,
];

/** Quick lookup by team ID */
export const teamById: Record<string, MockTeamData> = Object.fromEntries(
  allMockTeams.map((t) => [t.team.id, t])
);

/** Get all teams for a sport */
export function getTeamsForSport(sport: Sport): MockTeamData[] {
  switch (sport) {
    case "soccer":
      return soccerTeams;
    case "nba":
      return nbaTeams;
    case "nfl":
      return nflTeams;
    case "nhl":
      return nhlTeams;
    case "mlb":
      return mlbTeams;
  }
}
